// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.NetmailSearch_AdvanceSearch;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>MessageNetmailTab_SuperUser</b><br>
 * Generated     : <b>2014/06/20 3:50:20 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  June 20, 2014
 * @author Administrator
 */
public abstract class MessageNetmailTab_SuperUserHelper extends utilities.MySuperHelper
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * AdvancedSearchbutton: with default state.
	 *		.text : Advanced Search
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_advancedSearchbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_advancedSearchbutton"));
	}
	/**
	 * AdvancedSearchbutton: with specific test context and state.
	 *		.text : Advanced Search
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_advancedSearchbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_advancedSearchbutton"), anchor, flags);
	}
	
	/**
	 * ANDbutton: with default state.
	 *		.text : AND
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_anDbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_anDbutton"));
	}
	/**
	 * ANDbutton: with specific test context and state.
	 *		.text : AND
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_anDbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_anDbutton"), anchor, flags);
	}
	
	/**
	 * Applybutton: with default state.
	 *		.text : Apply
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_applybutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_applybutton"));
	}
	/**
	 * Applybutton: with specific test context and state.
	 *		.text : Apply
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_applybutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_applybutton"), anchor, flags);
	}
	
	/**
	 * Clearsubmit: with default state.
	 *		.text : Clear
	 * 		type : submit
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_clearsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_clearsubmit"));
	}
	/**
	 * Clearsubmit: with specific test context and state.
	 *		.text : Clear
	 * 		type : submit
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_clearsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_clearsubmit"), anchor, flags);
	}
	
	/**
	 * ORbutton: with default state.
	 *		.text : OR
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_oRbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_oRbutton"));
	}
	/**
	 * ORbutton: with specific test context and state.
	 *		.text : OR
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_oRbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_oRbutton"), anchor, flags);
	}
	
	/**
	 * Searchsubmit: with default state.
	 *		.text : Search
	 * 		type : submit
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text advanced-tb-icon
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_searchsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_searchsubmit"));
	}
	/**
	 * Searchsubmit: with specific test context and state.
	 *		.text : Search
	 * 		type : submit
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text advanced-tb-icon
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_searchsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_searchsubmit"), anchor, flags);
	}
	
	/**
	 * mbMessageBody: with default state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : about:blank
	 */
	protected DocumentTestObject document_mbMessageBody() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_mbMessageBody"));
	}
	/**
	 * mbMessageBody: with specific test context and state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : about:blank
	 */
	protected DocumentTestObject document_mbMessageBody(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_mbMessageBody"), anchor, flags);
	}
	
	/**
	 * mbMessageBody: with default state.
	 *		.class : Html.IFRAME
	 */
	protected StatelessGuiSubitemTestObject frame_mbMessageBody() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("frame_mbMessageBody"));
	}
	/**
	 * mbMessageBody: with specific test context and state.
	 *		.class : Html.IFRAME
	 */
	protected StatelessGuiSubitemTestObject frame_mbMessageBody(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("frame_mbMessageBody"), anchor, flags);
	}
	
	/**
	 * mbClose: with default state.
	 *		.className : x-tool x-tool-close
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_mbClose() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_mbClose"));
	}
	/**
	 * mbClose: with specific test context and state.
	 *		.className : x-tool x-tool-close
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_mbClose(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_mbClose"), anchor, flags);
	}
	
	/**
	 * advSearchNetmailTab: with default state.
	 *		.text : Netmail Search
	 * 		.class : Html.A
	 * 		class : x-tab-right
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_advSearchNetmailTab() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_advSearchNetmailTab"));
	}
	/**
	 * advSearchNetmailTab: with specific test context and state.
	 *		.text : Netmail Search
	 * 		.class : Html.A
	 * 		class : x-tab-right
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_advSearchNetmailTab(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_advSearchNetmailTab"), anchor, flags);
	}
	
	/**
	 * advanceSearchMessage: with default state.
	 *		.text : Messages
	 * 		.title : 
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_advanceSearchMessage() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_advanceSearchMessage"));
	}
	/**
	 * advanceSearchMessage: with specific test context and state.
	 *		.text : Messages
	 * 		.title : 
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_advanceSearchMessage(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_advanceSearchMessage"), anchor, flags);
	}
	
	/**
	 * clearSearch: with default state.
	 *		.text : (clear search)
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_clearSearch() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_clearSearch"));
	}
	/**
	 * clearSearch: with specific test context and state.
	 *		.text : (clear search)
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_clearSearch(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_clearSearch"), anchor, flags);
	}
	
	/**
	 * approximateSpelling: with default state.
	 *		.className : x-grid3-row-table
	 * 		.class : Html.TABLE
	 * 		.contentText : Approximate spelling
	 */
	protected StatelessGuiSubitemTestObject table_approximateSpelling() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_approximateSpelling"));
	}
	/**
	 * approximateSpelling: with specific test context and state.
	 *		.className : x-grid3-row-table
	 * 		.class : Html.TABLE
	 * 		.contentText : Approximate spelling
	 */
	protected StatelessGuiSubitemTestObject table_approximateSpelling(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_approximateSpelling"), anchor, flags);
	}
	
	/**
	 * exactPhrase: with default state.
	 *		.className : x-grid3-row-table
	 * 		.class : Html.TABLE
	 * 		.contentText : Exact phrase
	 */
	protected StatelessGuiSubitemTestObject table_exactPhrase() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_exactPhrase"));
	}
	/**
	 * exactPhrase: with specific test context and state.
	 *		.className : x-grid3-row-table
	 * 		.class : Html.TABLE
	 * 		.contentText : Exact phrase
	 */
	protected StatelessGuiSubitemTestObject table_exactPhrase(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_exactPhrase"), anchor, flags);
	}
	
	/**
	 * forbiddenTerm: with default state.
	 *		.className : x-grid3-row-table
	 * 		.class : Html.TABLE
	 * 		.contentText : Forbidden Terms
	 */
	protected StatelessGuiSubitemTestObject table_forbiddenTerm() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_forbiddenTerm"));
	}
	/**
	 * forbiddenTerm: with specific test context and state.
	 *		.className : x-grid3-row-table
	 * 		.class : Html.TABLE
	 * 		.contentText : Forbidden Terms
	 */
	protected StatelessGuiSubitemTestObject table_forbiddenTerm(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_forbiddenTerm"), anchor, flags);
	}
	
	/**
	 * proximitySearch: with default state.
	 *		.className : x-grid3-row-table
	 * 		.class : Html.TABLE
	 * 		.contentText : Proximity search
	 */
	protected StatelessGuiSubitemTestObject table_proximitySearch() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_proximitySearch"));
	}
	/**
	 * proximitySearch: with specific test context and state.
	 *		.className : x-grid3-row-table
	 * 		.class : Html.TABLE
	 * 		.contentText : Proximity search
	 */
	protected StatelessGuiSubitemTestObject table_proximitySearch(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_proximitySearch"), anchor, flags);
	}
	
	/**
	 * wordStartingWith: with default state.
	 *		.className : x-grid3-row-table
	 * 		.class : Html.TABLE
	 * 		.contentText : Words starting with
	 */
	protected StatelessGuiSubitemTestObject table_wordStartingWith() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_wordStartingWith"));
	}
	/**
	 * wordStartingWith: with specific test context and state.
	 *		.className : x-grid3-row-table
	 * 		.class : Html.TABLE
	 * 		.contentText : Words starting with
	 */
	protected StatelessGuiSubitemTestObject table_wordStartingWith(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_wordStartingWith"), anchor, flags);
	}
	
	/**
	 * mbFrom: with default state.
	 *		type : text
	 * 		.class : Html.INPUT.text
	 * 		name : from
	 * 		class : x-form-text x-form-field
	 */
	protected TextGuiTestObject text_mbFrom() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_mbFrom"));
	}
	/**
	 * mbFrom: with specific test context and state.
	 *		type : text
	 * 		.class : Html.INPUT.text
	 * 		name : from
	 * 		class : x-form-text x-form-field
	 */
	protected TextGuiTestObject text_mbFrom(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_mbFrom"), anchor, flags);
	}
	
	/**
	 * mbSubject: with default state.
	 *		type : text
	 * 		.class : Html.INPUT.text
	 * 		name : subject
	 * 		class : x-form-text x-form-field
	 */
	protected TextGuiTestObject text_mbSubject() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_mbSubject"));
	}
	/**
	 * mbSubject: with specific test context and state.
	 *		type : text
	 * 		.class : Html.INPUT.text
	 * 		name : subject
	 * 		class : x-form-text x-form-field
	 */
	protected TextGuiTestObject text_mbSubject(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_mbSubject"), anchor, flags);
	}
	
	/**
	 * mbTo: with default state.
	 *		type : text
	 * 		.class : Html.INPUT.text
	 * 		name : to
	 * 		class : x-form-text x-form-field x-trigger-noedit x-form-empty-field
	 */
	protected TextGuiTestObject text_mbTo() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_mbTo"));
	}
	/**
	 * mbTo: with specific test context and state.
	 *		type : text
	 * 		.class : Html.INPUT.text
	 * 		name : to
	 * 		class : x-form-text x-form-field x-trigger-noedit x-form-empty-field
	 */
	protected TextGuiTestObject text_mbTo(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_mbTo"), anchor, flags);
	}
	
	/**
	 * netmailSearch_Input: with default state.
	 *		.text : 
	 * 		type : text
	 * 		.class : Html.INPUT.text
	 * 		class : x-form-text x-form-field x-abs-layout-item
	 */
	protected TextGuiTestObject text_netmailSearch_Input() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_netmailSearch_Input"));
	}
	/**
	 * netmailSearch_Input: with specific test context and state.
	 *		.text : 
	 * 		type : text
	 * 		.class : Html.INPUT.text
	 * 		class : x-form-text x-form-field x-abs-layout-item
	 */
	protected TextGuiTestObject text_netmailSearch_Input(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_netmailSearch_Input"), anchor, flags);
	}
	
	/**
	 * sql: with default state.
	 *		.class : Html.TEXTAREA
	 * 		.name : sql
	 * 		class : x-form-textarea x-form-field x-abs-layout-item
	 */
	protected TextGuiTestObject text_sql() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_sql"));
	}
	/**
	 * sql: with specific test context and state.
	 *		.class : Html.TEXTAREA
	 * 		.name : sql
	 * 		class : x-form-textarea x-form-field x-abs-layout-item
	 */
	protected TextGuiTestObject text_sql(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_sql"), anchor, flags);
	}
	
	

	protected MessageNetmailTab_SuperUserHelper()
	{
		setScriptName("NetmailSearch_AdvanceSearch.MessageNetmailTab_SuperUser");
	}
	
}

