// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TC_831_NetmailSearch;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TS_1256</b><br>
 * Generated     : <b>2015/02/24 11:13:03 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  February 24, 2015
 * @author Administrator
 */
public abstract class TS_1256Helper extends utilities.MySuperHelper
{
	/**
	 * Preferencesbutton: with default state.
	 *		.text : Preferences
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_preferencesbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_preferencesbutton"));
	}
	/**
	 * Preferencesbutton: with specific test context and state.
	 *		.text : Preferences
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_preferencesbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_preferencesbutton"), anchor, flags);
	}
	
	/**
	 * bpMessage: with default state.
	 *		.class : Html.HtmlDocument
	 * 		.url : about:blank
	 */
	protected DocumentTestObject document_bpMessage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_bpMessage"));
	}
	/**
	 * bpMessage: with specific test context and state.
	 *		.class : Html.HtmlDocument
	 * 		.url : about:blank
	 */
	protected DocumentTestObject document_bpMessage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_bpMessage"), anchor, flags);
	}
	
	/**
	 * mbMessage: with default state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : about:blank
	 */
	protected DocumentTestObject document_mbMessage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_mbMessage"));
	}
	/**
	 * mbMessage: with specific test context and state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : about:blank
	 */
	protected DocumentTestObject document_mbMessage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_mbMessage"), anchor, flags);
	}
	
	/**
	 * spMessage: with default state.
	 *		.class : Html.HtmlDocument
	 * 		.url : about:blank
	 */
	protected DocumentTestObject document_spMessage() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_spMessage"));
	}
	/**
	 * spMessage: with specific test context and state.
	 *		.class : Html.HtmlDocument
	 * 		.url : about:blank
	 */
	protected DocumentTestObject document_spMessage(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_spMessage"), anchor, flags);
	}
	
	/**
	 * bottomPanel_extComp1307: with default state.
	 *		.offsetWidth : RegularExpression([1-9][0-9]*)
	 * 		.text : RegularExpression(Preview.*Properties.*)
	 * 		.screenLeft : RegularExpression([1-9][0-9]*)
	 * 		.className : RegularExpression(x-panel x-border-panel)
	 * 		.class : Html.DIV
	 * 		style : RegularExpression((?i).*top: [1-9][0-9]*px.*)
	 * 		.offsetHeight : RegularExpression([1-9][0-9]*)
	 * 		.offsetLeft : RegularExpression([1-9][0-9]*)
	 * 		.classIndex : 2
	 */
	protected GuiTestObject html_bottomPanel_extComp1307() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_bottomPanel_extComp1307"));
	}
	/**
	 * bottomPanel_extComp1307: with specific test context and state.
	 *		.offsetWidth : RegularExpression([1-9][0-9]*)
	 * 		.text : RegularExpression(Preview.*Properties.*)
	 * 		.screenLeft : RegularExpression([1-9][0-9]*)
	 * 		.className : RegularExpression(x-panel x-border-panel)
	 * 		.class : Html.DIV
	 * 		style : RegularExpression((?i).*top: [1-9][0-9]*px.*)
	 * 		.offsetHeight : RegularExpression([1-9][0-9]*)
	 * 		.offsetLeft : RegularExpression([1-9][0-9]*)
	 * 		.classIndex : 2
	 */
	protected GuiTestObject html_bottomPanel_extComp1307(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_bottomPanel_extComp1307"), anchor, flags);
	}
	
	/**
	 * extGen862: with default state.
	 *		.className : x-panel-body x-panel-body-noheader x-border-layout-ct
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_extGen278() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen278"));
	}
	/**
	 * extGen862: with specific test context and state.
	 *		.className : x-panel-body x-panel-body-noheader x-border-layout-ct
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_extGen278(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen278"), anchor, flags);
	}
	
	/**
	 * extGen3: with default state.
	 *		.class : Html.BODY
	 */
	protected GuiTestObject html_extGen3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen3"));
	}
	/**
	 * extGen3: with specific test context and state.
	 *		.class : Html.BODY
	 */
	protected GuiTestObject html_extGen3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen3"), anchor, flags);
	}
	
	/**
	 * extGen555: with default state.
	 *		.className : x-panel-body x-panel-body-noheader
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_extGen555() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen555"));
	}
	/**
	 * extGen555: with specific test context and state.
	 *		.className : x-panel-body x-panel-body-noheader
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_extGen555(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen555"), anchor, flags);
	}
	
	/**
	 * messageBoxClose: with default state.
	 *		.className : x-tool x-tool-close
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_messageBoxClose() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_messageBoxClose"));
	}
	/**
	 * messageBoxClose: with specific test context and state.
	 *		.className : x-tool x-tool-close
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_messageBoxClose(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_messageBoxClose"), anchor, flags);
	}
	
	/**
	 * topPanel_extComp1309: with default state.
	 *		.classIndex : 3
	 * 		.screenTop : RegularExpression([1-9][0-9]*)
	 * 		.className : RegularExpression(x-panel x-border-panel)
	 * 		.text : RegularExpression(Preview.*Properties.*)
	 * 		.offsetTop : 0
	 * 		.class : Html.DIV
	 * 		.offsetLeft : RegularExpression([1-9][0-9]*)
	 * 		.screenLeft : RegularExpression([1-9][0-9]*)
	 * 		.offsetWidth : RegularExpression([1-9][0-9]*)
	 * 		style : RegularExpression((?i).* top: 0px.*)
	 * 		.offsetHeight : RegularExpression([1-9][0-9]*)
	 */
	protected GuiTestObject html_topPanel_extComp1309() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_topPanel_extComp1309"));
	}
	/**
	 * topPanel_extComp1309: with specific test context and state.
	 *		.classIndex : 3
	 * 		.screenTop : RegularExpression([1-9][0-9]*)
	 * 		.className : RegularExpression(x-panel x-border-panel)
	 * 		.text : RegularExpression(Preview.*Properties.*)
	 * 		.offsetTop : 0
	 * 		.class : Html.DIV
	 * 		.offsetLeft : RegularExpression([1-9][0-9]*)
	 * 		.screenLeft : RegularExpression([1-9][0-9]*)
	 * 		.offsetWidth : RegularExpression([1-9][0-9]*)
	 * 		style : RegularExpression((?i).* top: 0px.*)
	 * 		.offsetHeight : RegularExpression([1-9][0-9]*)
	 */
	protected GuiTestObject html_topPanel_extComp1309(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_topPanel_extComp1309"), anchor, flags);
	}
	
	/**
	 * bottomPane: with default state.
	 *		.text : Bottom pane
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_bottomPane() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_bottomPane"));
	}
	/**
	 * bottomPane: with specific test context and state.
	 *		.text : Bottom pane
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_bottomPane(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_bottomPane"), anchor, flags);
	}
	
	/**
	 * noPreview: with default state.
	 *		.text : No preview
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_noPreview() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_noPreview"));
	}
	/**
	 * noPreview: with specific test context and state.
	 *		.text : No preview
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_noPreview(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_noPreview"), anchor, flags);
	}
	
	/**
	 * previewMenu: with default state.
	 *		.text : Preview
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-item-arrow
	 */
	protected GuiTestObject link_previewMenu() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_previewMenu"));
	}
	/**
	 * previewMenu: with specific test context and state.
	 *		.text : Preview
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-item-arrow
	 */
	protected GuiTestObject link_previewMenu(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_previewMenu"), anchor, flags);
	}
	
	/**
	 * sidePane: with default state.
	 *		.text : Side pane
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_sidePane() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_sidePane"));
	}
	/**
	 * sidePane: with specific test context and state.
	 *		.text : Side pane
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_sidePane(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_sidePane"), anchor, flags);
	}
	
	/**
	 * bpFROM: with default state.
	 *		type : text
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : from
	 * 		class : x-form-text x-form-field
	 */
	protected TextGuiTestObject text_bpFROM() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_bpFROM"));
	}
	/**
	 * bpFROM: with specific test context and state.
	 *		type : text
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : from
	 * 		class : x-form-text x-form-field
	 */
	protected TextGuiTestObject text_bpFROM(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_bpFROM"), anchor, flags);
	}
	
	/**
	 * bpSubject: with default state.
	 *		type : text
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : subject
	 * 		class : x-form-text x-form-field
	 */
	protected TextGuiTestObject text_bpSubject() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_bpSubject"));
	}
	/**
	 * bpSubject: with specific test context and state.
	 *		type : text
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : subject
	 * 		class : x-form-text x-form-field
	 */
	protected TextGuiTestObject text_bpSubject(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_bpSubject"), anchor, flags);
	}
	
	/**
	 * bpTO: with default state.
	 *		type : text
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : RegularExpression(to|cc)
	 * 		class : x-form-text x-form-field x-trigger-noedit x-form-empty-field
	 */
	protected TextGuiTestObject text_bpTO() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_bpTO"));
	}
	/**
	 * bpTO: with specific test context and state.
	 *		type : text
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : RegularExpression(to|cc)
	 * 		class : x-form-text x-form-field x-trigger-noedit x-form-empty-field
	 */
	protected TextGuiTestObject text_bpTO(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_bpTO"), anchor, flags);
	}
	
	/**
	 * mbFrom: with default state.
	 *		.text : 
	 * 		type : text
	 * 		.title : 
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : from
	 * 		.classIndex : 0
	 * 		class : x-form-text x-form-field
	 */
	protected TextGuiTestObject text_mbFrom() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_mbFrom"));
	}
	/**
	 * mbFrom: with specific test context and state.
	 *		.text : 
	 * 		type : text
	 * 		.title : 
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : from
	 * 		.classIndex : 0
	 * 		class : x-form-text x-form-field
	 */
	protected TextGuiTestObject text_mbFrom(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_mbFrom"), anchor, flags);
	}
	
	/**
	 * mbSubject: with default state.
	 *		.text : 
	 * 		type : text
	 * 		.title : 
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : subject
	 * 		class : x-form-text x-form-field
	 */
	protected TextGuiTestObject text_mbSubject() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_mbSubject"));
	}
	/**
	 * mbSubject: with specific test context and state.
	 *		.text : 
	 * 		type : text
	 * 		.title : 
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : subject
	 * 		class : x-form-text x-form-field
	 */
	protected TextGuiTestObject text_mbSubject(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_mbSubject"), anchor, flags);
	}
	
	/**
	 * mbTO: with default state.
	 *		.text : 
	 * 		type : text
	 * 		.title : 
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : to
	 * 		class : x-form-text x-form-field x-trigger-noedit x-form-empty-field
	 */
	protected TextGuiTestObject text_mbTO() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_mbTO"));
	}
	/**
	 * mbTO: with specific test context and state.
	 *		.text : 
	 * 		type : text
	 * 		.title : 
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : to
	 * 		class : x-form-text x-form-field x-trigger-noedit x-form-empty-field
	 */
	protected TextGuiTestObject text_mbTO(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_mbTO"), anchor, flags);
	}
	
	/**
	 * spFrom: with default state.
	 *		type : text
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : from
	 * 		class : x-form-text x-form-field
	 */
	protected TextGuiTestObject text_spFrom() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_spFrom"));
	}
	/**
	 * spFrom: with specific test context and state.
	 *		type : text
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : from
	 * 		class : x-form-text x-form-field
	 */
	protected TextGuiTestObject text_spFrom(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_spFrom"), anchor, flags);
	}
	
	/**
	 * spSubject: with default state.
	 *		type : text
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : subject
	 * 		class : x-form-text x-form-field
	 */
	protected TextGuiTestObject text_spSubject() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_spSubject"));
	}
	/**
	 * spSubject: with specific test context and state.
	 *		type : text
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : subject
	 * 		class : x-form-text x-form-field
	 */
	protected TextGuiTestObject text_spSubject(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_spSubject"), anchor, flags);
	}
	
	/**
	 * spTO: with default state.
	 *		type : text
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : RegularExpression(to|cc)
	 * 		class : x-form-text x-form-field x-trigger-noedit x-form-empty-field
	 */
	protected TextGuiTestObject text_spTO() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_spTO"));
	}
	/**
	 * spTO: with specific test context and state.
	 *		type : text
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : RegularExpression(to|cc)
	 * 		class : x-form-text x-form-field x-trigger-noedit x-form-empty-field
	 */
	protected TextGuiTestObject text_spTO(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_spTO"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point sidePanel_IE object in the SUT.
	 */
	protected IFtVerificationPoint sidePanel_IEVP() 
	{
		return vp("sidePanel_IE");
	}
	protected IFtVerificationPoint sidePanel_IEVP(TestObject anchor)
	{
		return vp("sidePanel_IE", anchor);
	}
	
	/**
	 * Locate and return the verification point thebottompanel_ie object in the SUT.
	 */
	protected IFtVerificationPoint thebottompanel_ieVP() 
	{
		return vp("thebottompanel_ie");
	}
	protected IFtVerificationPoint thebottompanel_ieVP(TestObject anchor)
	{
		return vp("thebottompanel_ie", anchor);
	}
	
	

	protected TS_1256Helper()
	{
		setScriptName("TC_831_NetmailSearch.TS_1256");
	}
	
}

