// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TC_831_NetmailSearch;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TS_996</b><br>
 * Generated     : <b>2014/05/28 12:58:17 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  May 28, 2014
 * @author Administrator
 */
public abstract class TS_996Helper extends utilities.MySuperHelper
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * adminbutton: with default state.
	 *		.text : RegularExpression(.*)
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class : RegularExpression(.*x-btn-text)
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_adminbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_adminbutton"));
	}
	/**
	 * adminbutton: with specific test context and state.
	 *		.text : RegularExpression(.*)
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class : RegularExpression(.*x-btn-text)
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_adminbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_adminbutton"), anchor, flags);
	}
	
	/**
	 * Preferencesbutton: with default state.
	 *		.text : Preferences
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class : RegularExpression(.*x-btn-text.*)
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_preferencesbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_preferencesbutton"));
	}
	/**
	 * Preferencesbutton: with specific test context and state.
	 *		.text : Preferences
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class : RegularExpression(.*x-btn-text.*)
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_preferencesbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_preferencesbutton"), anchor, flags);
	}
	
	/**
	 * netmailSearch: with default state.
	 *		.title : netmail search
	 * 		.class : Html.HtmlDocument
	 */
	protected DocumentTestObject document_netmailSearch() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_netmailSearch"));
	}
	/**
	 * netmailSearch: with specific test context and state.
	 *		.title : netmail search
	 * 		.class : Html.HtmlDocument
	 */
	protected DocumentTestObject document_netmailSearch(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_netmailSearch"), anchor, flags);
	}
	
	/**
	 * highlightSearchTerm: with default state.
	 *		.text : Highlight Search Terms
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item
	 */
	protected GuiTestObject link_highlightSearchTerm() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_highlightSearchTerm"));
	}
	/**
	 * highlightSearchTerm: with specific test context and state.
	 *		.text : Highlight Search Terms
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item
	 */
	protected GuiTestObject link_highlightSearchTerm(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_highlightSearchTerm"), anchor, flags);
	}
	
	/**
	 * pageSize_100: with default state.
	 *		.text : 100
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_pageSize_100() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize_100"));
	}
	/**
	 * pageSize_100: with specific test context and state.
	 *		.text : 100
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_pageSize_100(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize_100"), anchor, flags);
	}
	
	/**
	 * pageSize_20: with default state.
	 *		.text : 20
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_pageSize_20() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize_20"));
	}
	/**
	 * pageSize_20: with specific test context and state.
	 *		.text : 20
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_pageSize_20(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize_20"), anchor, flags);
	}
	
	/**
	 * pageSize_200: with default state.
	 *		.text : 200
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_pageSize_200() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize_200"));
	}
	/**
	 * pageSize_200: with specific test context and state.
	 *		.text : 200
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_pageSize_200(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize_200"), anchor, flags);
	}
	
	/**
	 * pageSize_50: with default state.
	 *		.text : 50
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_pageSize_50() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize_50"));
	}
	/**
	 * pageSize_50: with specific test context and state.
	 *		.text : 50
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_pageSize_50(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize_50"), anchor, flags);
	}
	
	/**
	 * preference_pageSize: with default state.
	 *		.text : Page Size
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-item-arrow
	 */
	protected GuiTestObject link_preference_pageSize() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_preference_pageSize"));
	}
	/**
	 * preference_pageSize: with specific test context and state.
	 *		.text : Page Size
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-item-arrow
	 */
	protected GuiTestObject link_preference_pageSize(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_preference_pageSize"), anchor, flags);
	}
	
	/**
	 * userDD_About: with default state.
	 *		.text : About
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 */
	protected GuiTestObject link_userDD_About() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_About"));
	}
	/**
	 * userDD_About: with specific test context and state.
	 *		.text : About
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 */
	protected GuiTestObject link_userDD_About(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_About"), anchor, flags);
	}
	
	/**
	 * userDD_Accessibility: with default state.
	 *		.text : Accessibility
	 * 		.href : http://10.10.24.80:8888/index.html#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_userDD_Accessibility() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_Accessibility"));
	}
	/**
	 * userDD_Accessibility: with specific test context and state.
	 *		.text : Accessibility
	 * 		.href : http://10.10.24.80:8888/index.html#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_userDD_Accessibility(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_Accessibility"), anchor, flags);
	}
	
	/**
	 * userDD_Blue: with default state.
	 *		.text : Blue
	 * 		.href : http://10.10.24.80:8888/index.html#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_userDD_Blue() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_Blue"));
	}
	/**
	 * userDD_Blue: with specific test context and state.
	 *		.text : Blue
	 * 		.href : http://10.10.24.80:8888/index.html#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_userDD_Blue(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_Blue"), anchor, flags);
	}
	
	/**
	 * userDD_Default: with default state.
	 *		.text : Default (grey)
	 * 		.href : http://10.10.24.80:8888/index.html#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_userDD_Default() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_Default"));
	}
	/**
	 * userDD_Default: with specific test context and state.
	 *		.text : Default (grey)
	 * 		.href : http://10.10.24.80:8888/index.html#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_userDD_Default(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_Default"), anchor, flags);
	}
	
	/**
	 * userDD_English: with default state.
	 *		.text : English
	 * 		.href : http://10.10.24.80:8888/index.html#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_userDD_English() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_English"));
	}
	/**
	 * userDD_English: with specific test context and state.
	 *		.text : English
	 * 		.href : http://10.10.24.80:8888/index.html#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_userDD_English(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_English"), anchor, flags);
	}
	
	/**
	 * userDD_Francais: with default state.
	 *		.text : Français
	 * 		.href : http://10.10.24.80:8888/index.html#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_userDD_Francais() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_Francais"));
	}
	/**
	 * userDD_Francais: with specific test context and state.
	 *		.text : Français
	 * 		.href : http://10.10.24.80:8888/index.html#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_userDD_Francais(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_Francais"), anchor, flags);
	}
	
	/**
	 * userDD_FrenchCanadian: with default state.
	 *		.text : Français (Canadien)
	 * 		.href : http://10.10.24.80:8888/index.html#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_userDD_FrenchCanadian() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_FrenchCanadian"));
	}
	/**
	 * userDD_FrenchCanadian: with specific test context and state.
	 *		.text : Français (Canadien)
	 * 		.href : http://10.10.24.80:8888/index.html#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_userDD_FrenchCanadian(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_FrenchCanadian"), anchor, flags);
	}
	
	/**
	 * userDD_Help: with default state.
	 *		.text : Help
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 */
	protected GuiTestObject link_userDD_Help() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_Help"));
	}
	/**
	 * userDD_Help: with specific test context and state.
	 *		.text : Help
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 */
	protected GuiTestObject link_userDD_Help(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_Help"), anchor, flags);
	}
	
	/**
	 * userDD_Language: with default state.
	 *		.text : Language
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-item-arrow
	 */
	protected GuiTestObject link_userDD_Language() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_Language"));
	}
	/**
	 * userDD_Language: with specific test context and state.
	 *		.text : Language
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-item-arrow
	 */
	protected GuiTestObject link_userDD_Language(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_Language"), anchor, flags);
	}
	
	/**
	 * userDD_Logout: with default state.
	 *		.text : Log out
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 */
	protected GuiTestObject link_userDD_Logout() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_Logout"));
	}
	/**
	 * userDD_Logout: with specific test context and state.
	 *		.text : Log out
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 */
	protected GuiTestObject link_userDD_Logout(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_Logout"), anchor, flags);
	}
	
	/**
	 * userDD_Theme: with default state.
	 *		.text : Theme
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-item-arrow
	 */
	protected GuiTestObject link_userDD_Theme() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_Theme"));
	}
	/**
	 * userDD_Theme: with specific test context and state.
	 *		.text : Theme
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-item-arrow
	 */
	protected GuiTestObject link_userDD_Theme(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDD_Theme"), anchor, flags);
	}
	
	/**
	 * quickSearchField0: with default state.
	 *		.text : 
	 * 		type : text
	 * 		.id : quickSearchField0
	 * 		.title : 
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : quickSearchField0
	 * 		class : x-form-text x-form-field search_field_effect x-form-empty-field
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_quickSearchField0() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_quickSearchField0"));
	}
	/**
	 * quickSearchField0: with specific test context and state.
	 *		.text : 
	 * 		type : text
	 * 		.id : quickSearchField0
	 * 		.title : 
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : quickSearchField0
	 * 		class : x-form-text x-form-field search_field_effect x-form-empty-field
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_quickSearchField0(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_quickSearchField0"), anchor, flags);
	}
	
	

	protected TS_996Helper()
	{
		setScriptName("TC_831_NetmailSearch.TS_996");
	}
	
}

