// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TC_831_NetmailSearch;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TS_995</b><br>
 * Generated     : <b>2015/04/08 5:48:32 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  April 08, 2015
 * @author Administrator
 */
public abstract class TS_995Helper extends utilities.MySuperHelper
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * adminbutton: with default state.
	 *		.text : admin
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_adminbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_adminbutton"));
	}
	/**
	 * adminbutton: with specific test context and state.
	 *		.text : admin
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_adminbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_adminbutton"), anchor, flags);
	}
	
	/**
	 * button: with default state.
	 *		.text : 
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text search-tb-icon
	 */
	protected GuiTestObject button_button() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_button"));
	}
	/**
	 * button: with specific test context and state.
	 *		.text : 
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text search-tb-icon
	 */
	protected GuiTestObject button_button(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_button"), anchor, flags);
	}
	
	/**
	 * Cancelbutton: with default state.
	 *		.text : Cancel
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_cancelbutton2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_cancelbutton2"));
	}
	/**
	 * Cancelbutton: with specific test context and state.
	 *		.text : Cancel
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_cancelbutton2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_cancelbutton2"), anchor, flags);
	}
	
	/**
	 * CaseList_Cancelbutton: with default state.
	 *		.text : Close this window
	 * 		type : button
	 * 		.type : button
	 * 		.class : Html.BUTTON
	 * 		class :  x-btn-text cancel-tb-icon
	 */
	protected GuiTestObject button_caseList_Cancelbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_caseList_Cancelbutton"));
	}
	/**
	 * CaseList_Cancelbutton: with specific test context and state.
	 *		.text : Close this window
	 * 		type : button
	 * 		.type : button
	 * 		.class : Html.BUTTON
	 * 		class :  x-btn-text cancel-tb-icon
	 */
	protected GuiTestObject button_caseList_Cancelbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_caseList_Cancelbutton"), anchor, flags);
	}
	
	/**
	 * CaseManagementbutton: with default state.
	 *		.text : Case Management
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text edit-tb-icon
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_caseManagementbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_caseManagementbutton"));
	}
	/**
	 * CaseManagementbutton: with specific test context and state.
	 *		.text : Case Management
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text edit-tb-icon
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_caseManagementbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_caseManagementbutton"), anchor, flags);
	}
	
	/**
	 * CaseOpen: with default state.
	 *		.text : Open Case
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		.contentText : Open Case
	 * 		class :  x-btn-text load-tb-icon
	 */
	protected GuiTestObject button_caseOpen() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_caseOpen"));
	}
	/**
	 * CaseOpen: with specific test context and state.
	 *		.text : Open Case
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		.contentText : Open Case
	 * 		class :  x-btn-text load-tb-icon
	 */
	protected GuiTestObject button_caseOpen(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_caseOpen"), anchor, flags);
	}
	
	/**
	 * Continuebutton: with default state.
	 *		.text : RegularExpression(Continue|Continuer|Fortsetzen)
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_continuebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_continuebutton"));
	}
	/**
	 * Continuebutton: with specific test context and state.
	 *		.text : RegularExpression(Continue|Continuer|Fortsetzen)
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_continuebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_continuebutton"), anchor, flags);
	}
	
	/**
	 * EditCasebutton: with default state.
	 *		.text : Edit Case
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text edit-tb-icon
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_editCasebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_editCasebutton"));
	}
	/**
	 * EditCasebutton: with specific test context and state.
	 *		.text : Edit Case
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text edit-tb-icon
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_editCasebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_editCasebutton"), anchor, flags);
	}
	
	/**
	 * Languagebutton: with default state.
	 *		.text : Language
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_languagebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_languagebutton"));
	}
	/**
	 * Languagebutton: with specific test context and state.
	 *		.text : Language
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_languagebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_languagebutton"), anchor, flags);
	}
	
	/**
	 * Loginbutton: with default state.
	 *		.text : Login
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_loginbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_loginbutton"));
	}
	/**
	 * Loginbutton: with specific test context and state.
	 *		.text : Login
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_loginbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_loginbutton"), anchor, flags);
	}
	
	/**
	 * NewCase_Cancelbutton: with default state.
	 *		.text : Cancel
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_newCase_Cancelbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_newCase_Cancelbutton"));
	}
	/**
	 * NewCase_Cancelbutton: with specific test context and state.
	 *		.text : Cancel
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_newCase_Cancelbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_newCase_Cancelbutton"), anchor, flags);
	}
	
	/**
	 * NewCasebutton: with default state.
	 *		.text : New Case
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text new-tb-icon
	 */
	protected GuiTestObject button_newCasebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_newCasebutton"));
	}
	/**
	 * NewCasebutton: with specific test context and state.
	 *		.text : New Case
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text new-tb-icon
	 */
	protected GuiTestObject button_newCasebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_newCasebutton"), anchor, flags);
	}
	
	/**
	 * paginationFirstPageButton: with default state.
	 *		.text : 
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-first)
	 */
	protected GuiTestObject button_paginationFirstPageButt() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_paginationFirstPageButt"));
	}
	/**
	 * paginationFirstPageButton: with specific test context and state.
	 *		.text : 
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-first)
	 */
	protected GuiTestObject button_paginationFirstPageButt(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_paginationFirstPageButt"), anchor, flags);
	}
	
	/**
	 * paginationNextButton: with default state.
	 *		.text : 
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-next)
	 */
	protected GuiTestObject button_paginationNextButton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_paginationNextButton"));
	}
	/**
	 * paginationNextButton: with specific test context and state.
	 *		.text : 
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-next)
	 */
	protected GuiTestObject button_paginationNextButton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_paginationNextButton"), anchor, flags);
	}
	
	/**
	 * Preferencesbutton: with default state.
	 *		.text : Preferences
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_preferencesbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_preferencesbutton"));
	}
	/**
	 * Preferencesbutton: with specific test context and state.
	 *		.text : Preferences
	 * 		.type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_preferencesbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_preferencesbutton"), anchor, flags);
	}
	
	/**
	 * Yesbutton: with default state.
	 *		.text : Yes
	 * 		.type : button
	 * 		.value : Yes
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_yesbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_yesbutton"));
	}
	/**
	 * Yesbutton: with specific test context and state.
	 *		.text : Yes
	 * 		.type : button
	 * 		.value : Yes
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_yesbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_yesbutton"), anchor, flags);
	}
	
	/**
	 * netmailSearch: with default state.
	 *		.title : RegularExpression((?i)netmail search)
	 * 		.class : Html.HtmlDocument
	 */
	protected DocumentTestObject document_netmailSearch() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_netmailSearch"));
	}
	/**
	 * netmailSearch: with specific test context and state.
	 *		.title : RegularExpression((?i)netmail search)
	 * 		.class : Html.HtmlDocument
	 */
	protected DocumentTestObject document_netmailSearch(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_netmailSearch"), anchor, flags);
	}
	
	/**
	 * CaseListDIV_extGen166: with default state.
	 *		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_caseListDIV_extGen166() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_caseListDIV_extGen166"));
	}
	/**
	 * CaseListDIV_extGen166: with specific test context and state.
	 *		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_caseListDIV_extGen166(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_caseListDIV_extGen166"), anchor, flags);
	}
	
	/**
	 * DisplayingXofX: with default state.
	 *		.text : RegularExpression(Displaying.*of.*)
	 * 		.className : xtb-text
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_displayingXofX() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_displayingXofX"));
	}
	/**
	 * DisplayingXofX: with specific test context and state.
	 *		.text : RegularExpression(Displaying.*of.*)
	 * 		.className : xtb-text
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_displayingXofX(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_displayingXofX"), anchor, flags);
	}
	
	/**
	 * extGen13: with default state.
	 *		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_extGen13() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen13"));
	}
	/**
	 * extGen13: with specific test context and state.
	 *		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_extGen13(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen13"), anchor, flags);
	}
	
	/**
	 * extGen2246: with default state.
	 *		.text : Highlight Search Terms
	 * 		.className : x-menu-item-text
	 * 		.title : 
	 * 		.class : Html.SPAN
	 */
	protected GuiTestObject html_extGen2246() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen2246"));
	}
	/**
	 * extGen2246: with specific test context and state.
	 *		.text : Highlight Search Terms
	 * 		.className : x-menu-item-text
	 * 		.title : 
	 * 		.class : Html.SPAN
	 */
	protected GuiTestObject html_extGen2246(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen2246"), anchor, flags);
	}
	
	/**
	 * extGen2246: with default state.
	 *		.text : Highlight Search Terms
	 * 		.className : x-menu-item-text
	 * 		.title : 
	 * 		.class : Html.SPAN
	 */
	protected GuiTestObject html_extGen2246_2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen2246_2"));
	}
	/**
	 * extGen2246: with specific test context and state.
	 *		.text : Highlight Search Terms
	 * 		.className : x-menu-item-text
	 * 		.title : 
	 * 		.class : Html.SPAN
	 */
	protected GuiTestObject html_extGen2246_2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen2246_2"), anchor, flags);
	}
	
	/**
	 * extGen2274: with default state.
	 *		.text : 200
	 * 		.className : x-menu-item-text
	 * 		.title : 
	 * 		.class : Html.SPAN
	 */
	protected GuiTestObject html_extGen2274() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen2274"));
	}
	/**
	 * extGen2274: with specific test context and state.
	 *		.text : 200
	 * 		.className : x-menu-item-text
	 * 		.title : 
	 * 		.class : Html.SPAN
	 */
	protected GuiTestObject html_extGen2274(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen2274"), anchor, flags);
	}
	
	/**
	 * extGen528: with default state.
	 *		.class : Html.EM
	 */
	protected GuiTestObject html_extGen528() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen528"));
	}
	/**
	 * extGen528: with specific test context and state.
	 *		.class : Html.EM
	 */
	protected GuiTestObject html_extGen528(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen528"), anchor, flags);
	}
	
	/**
	 * extGen543: with default state.
	 *		.text : Log out
	 * 		.className : x-menu-item-text
	 * 		.title : 
	 * 		.class : Html.SPAN
	 */
	protected GuiTestObject html_extGen543() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen543"));
	}
	/**
	 * extGen543: with specific test context and state.
	 *		.text : Log out
	 * 		.className : x-menu-item-text
	 * 		.title : 
	 * 		.class : Html.SPAN
	 */
	protected GuiTestObject html_extGen543(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen543"), anchor, flags);
	}
	
	/**
	 * extGen524: with default state.
	 *		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_extGen811() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen811"));
	}
	/**
	 * extGen524: with specific test context and state.
	 *		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_extGen811(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen811"), anchor, flags);
	}
	
	/**
	 * extGen95: with default state.
	 *		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_extGen95() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen95"));
	}
	/**
	 * extGen95: with specific test context and state.
	 *		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_extGen95(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen95"), anchor, flags);
	}
	
	/**
	 * extGen95: with default state.
	 *		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_extGen95_2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen95_2"));
	}
	/**
	 * extGen95: with specific test context and state.
	 *		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_extGen95_2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen95_2"), anchor, flags);
	}
	
	/**
	 * quickCaseList2: with default state.
	 *		.className : x-combo-list-inner
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_quickCaseList2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_quickCaseList2"));
	}
	/**
	 * quickCaseList2: with specific test context and state.
	 *		.className : x-combo-list-inner
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_quickCaseList2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_quickCaseList2"), anchor, flags);
	}
	
	/**
	 * extGen12: with default state.
	 *		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_quickCaseList_extGen579() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_quickCaseList_extGen579"));
	}
	/**
	 * extGen12: with specific test context and state.
	 *		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_quickCaseList_extGen579(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_quickCaseList_extGen579"), anchor, flags);
	}
	
	/**
	 * extComp1036: with default state.
	 *		.class : Html.DIV
	 * 		.classIndex : NR:Range[15 .. 25]
	 */
	protected GuiTestObject html_roleSelectionWindow() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_roleSelectionWindow"));
	}
	/**
	 * extComp1036: with specific test context and state.
	 *		.class : Html.DIV
	 * 		.classIndex : NR:Range[15 .. 25]
	 */
	protected GuiTestObject html_roleSelectionWindow(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_roleSelectionWindow"), anchor, flags);
	}
	
	/**
	 * roleSelectionWindow: with default state.
	 *		.id : roleSelectionWindow
	 * 		.className :  x-window x-window-noborder
	 * 		.class : Html.DIV
	 * 		.classIndex : 7
	 */
	protected GuiTestObject html_roleSelectionWindow2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_roleSelectionWindow2"));
	}
	/**
	 * roleSelectionWindow: with specific test context and state.
	 *		.id : roleSelectionWindow
	 * 		.className :  x-window x-window-noborder
	 * 		.class : Html.DIV
	 * 		.classIndex : 7
	 */
	protected GuiTestObject html_roleSelectionWindow2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_roleSelectionWindow2"), anchor, flags);
	}
	
	/**
	 * UserListDIV_extGen80: with default state.
	 *		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_userListDIV_extGen80() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_userListDIV_extGen80"));
	}
	/**
	 * UserListDIV_extGen80: with specific test context and state.
	 *		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_userListDIV_extGen80(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_userListDIV_extGen80"), anchor, flags);
	}
	
	/**
	 * s: with default state.
	 *		.alt : 
	 * 		.id : ext-gen126
	 * 		.src : http://10.10.24.80:8888/ext/resources/images/default/s.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_s() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_s"));
	}
	/**
	 * s: with specific test context and state.
	 *		.alt : 
	 * 		.id : ext-gen126
	 * 		.src : http://10.10.24.80:8888/ext/resources/images/default/s.gif
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_s(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_s"), anchor, flags);
	}
	
	/**
	 * highlight_extComp1510: with default state.
	 *		.text : Highlight Search Terms
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item x-menu-check-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_highlight_extComp1510() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_highlight_extComp1510"));
	}
	/**
	 * highlight_extComp1510: with specific test context and state.
	 *		.text : Highlight Search Terms
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item x-menu-check-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_highlight_extComp1510(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_highlight_extComp1510"), anchor, flags);
	}
	
	/**
	 * Page100: with default state.
	 *		.text : 100
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_page100() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_page100"));
	}
	/**
	 * Page100: with specific test context and state.
	 *		.text : 100
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_page100(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_page100"), anchor, flags);
	}
	
	/**
	 * Page20: with default state.
	 *		.text : 20
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_page20() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_page20"));
	}
	/**
	 * Page20: with specific test context and state.
	 *		.text : 20
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_page20(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_page20"), anchor, flags);
	}
	
	/**
	 * Page200: with default state.
	 *		.text : 200
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_page200() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_page200"));
	}
	/**
	 * Page200: with specific test context and state.
	 *		.text : 200
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_page200(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_page200"), anchor, flags);
	}
	
	/**
	 * Page50: with default state.
	 *		.text : 50
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_page50() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_page50"));
	}
	/**
	 * Page50: with specific test context and state.
	 *		.text : 50
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_page50(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_page50"), anchor, flags);
	}
	
	/**
	 * Preference_PageSize: with default state.
	 *		.text : Page Size
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.classIndex : 0
	 * 		class : x-menu-item x-menu-item-arrow
	 */
	protected GuiTestObject link_pageSize() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize"));
	}
	/**
	 * Preference_PageSize: with specific test context and state.
	 *		.text : Page Size
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.classIndex : 0
	 * 		class : x-menu-item x-menu-item-arrow
	 */
	protected GuiTestObject link_pageSize(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize"), anchor, flags);
	}
	
	/**
	 * userDropDown_Language: with default state.
	 *		.text : Language
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-item-arrow
	 */
	protected GuiTestObject link_userDropDown_Language() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDropDown_Language"));
	}
	/**
	 * userDropDown_Language: with specific test context and state.
	 *		.text : Language
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-item-arrow
	 */
	protected GuiTestObject link_userDropDown_Language(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDropDown_Language"), anchor, flags);
	}
	
	/**
	 * userDropDown_Theme: with default state.
	 *		.text : Theme
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-item-arrow
	 */
	protected GuiTestObject link_userDropDown_Theme() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDropDown_Theme"));
	}
	/**
	 * userDropDown_Theme: with specific test context and state.
	 *		.text : Theme
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-item-arrow
	 */
	protected GuiTestObject link_userDropDown_Theme(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_userDropDown_Theme"), anchor, flags);
	}
	
	/**
	 * exportMenuBtn: with default state.
	 *		.text : Export Case
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		class : x-btn  x-btn-noicon x-btn-over
	 * 		.classIndex : 4
	 */
	protected StatelessGuiSubitemTestObject table_exportMenuBtn() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_exportMenuBtn"));
	}
	/**
	 * exportMenuBtn: with specific test context and state.
	 *		.text : Export Case
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		class : x-btn  x-btn-noicon x-btn-over
	 * 		.classIndex : 4
	 */
	protected StatelessGuiSubitemTestObject table_exportMenuBtn(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_exportMenuBtn"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.text : Normal User
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		class : x-grid3-row-table
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.text : Normal User
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		class : x-grid3-row-table
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"), anchor, flags);
	}
	
	/**
	 * HtmlTable_6: with default state.
	 *		.text : goose New 12/17/12
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		class : x-grid3-row-table
	 * 		.classIndex : 6
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_6() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_6"));
	}
	/**
	 * HtmlTable_6: with specific test context and state.
	 *		.text : goose New 12/17/12
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		class : x-grid3-row-table
	 * 		.classIndex : 6
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_6(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_6"), anchor, flags);
	}
	
	/**
	 * tmaLanguageBtn: with default state.
	 *		.text : Language
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		class : x-btn tma-language-btn x-btn-noicon x-btn-over
	 * 		.classIndex : 1
	 */
	protected StatelessGuiSubitemTestObject table_tmaLanguageBtn() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_tmaLanguageBtn"));
	}
	/**
	 * tmaLanguageBtn: with specific test context and state.
	 *		.text : Language
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		class : x-btn tma-language-btn x-btn-noicon x-btn-over
	 * 		.classIndex : 1
	 */
	protected StatelessGuiSubitemTestObject table_tmaLanguageBtn(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_tmaLanguageBtn"), anchor, flags);
	}
	
	/**
	 * userDropDown2: with default state.
	 *		.text : RegularExpression(admin.*)
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		class : x-btn headerLink x-btn-noicon x-box-item
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_userDropDown2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_userDropDown2"));
	}
	/**
	 * userDropDown2: with specific test context and state.
	 *		.text : RegularExpression(admin.*)
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		class : x-btn headerLink x-btn-noicon x-box-item
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_userDropDown2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_userDropDown2"), anchor, flags);
	}
	
	/**
	 * _3: with default state.
	 *		.text : 
	 * 		type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		name : 
	 * 		.classIndex : 0
	 * 		class : x-form-text x-form-field x-form-num-field x-tbar-page-number
	 */
	protected TextGuiTestObject text__3() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__3"));
	}
	/**
	 * _3: with specific test context and state.
	 *		.text : 
	 * 		type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		name : 
	 * 		.classIndex : 0
	 * 		class : x-form-text x-form-field x-form-num-field x-tbar-page-number
	 */
	protected TextGuiTestObject text__3(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__3"), anchor, flags);
	}
	
	/**
	 * pwd: with default state.
	 *		.id : tmaLoginPassword
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : pwd
	 * 		class : x-form-text x-form-field
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_pwd() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_pwd"));
	}
	/**
	 * pwd: with specific test context and state.
	 *		.id : tmaLoginPassword
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : pwd
	 * 		class : x-form-text x-form-field
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_pwd(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_pwd"), anchor, flags);
	}
	
	/**
	 * quickCaseComboBox: with default state.
	 *		.text : 
	 * 		.id : quickCaseComboBox
	 * 		.type : text
	 * 		.title : 
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		class : x-form-text x-form-field x-trigger-noedit
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_quickCaseComboBox() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_quickCaseComboBox"));
	}
	/**
	 * quickCaseComboBox: with specific test context and state.
	 *		.text : 
	 * 		.id : quickCaseComboBox
	 * 		.type : text
	 * 		.title : 
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		class : x-form-text x-form-field x-trigger-noedit
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_quickCaseComboBox(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_quickCaseComboBox"), anchor, flags);
	}
	
	/**
	 * quickSearchField0: with default state.
	 *		type : text
	 * 		.id : quickSearchField0
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : quickSearchField0
	 */
	protected TextGuiTestObject text_quickSearchField0() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_quickSearchField0"));
	}
	/**
	 * quickSearchField0: with specific test context and state.
	 *		type : text
	 * 		.id : quickSearchField0
	 * 		.class : RegularExpression(Html\.INPUT\.text|Html\.INPUT)
	 * 		name : quickSearchField0
	 */
	protected TextGuiTestObject text_quickSearchField0(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_quickSearchField0"), anchor, flags);
	}
	
	/**
	 * uid: with default state.
	 *		.text : 
	 * 		.id : tmaLoginUsername
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : uid
	 * 		class : x-form-text x-form-field
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_uid() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_uid"));
	}
	/**
	 * uid: with specific test context and state.
	 *		.text : 
	 * 		.id : tmaLoginUsername
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : uid
	 * 		class : x-form-text x-form-field
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_uid(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_uid"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point IE_loginScreen object in the SUT.
	 */
	protected IFtVerificationPoint IE_loginScreenVP() 
	{
		return vp("IE_loginScreen");
	}
	protected IFtVerificationPoint IE_loginScreenVP(TestObject anchor)
	{
		return vp("IE_loginScreen", anchor);
	}
	
	/**
	 * Locate and return the verification point IE_roleSelectionWindow object in the SUT.
	 */
	protected IFtVerificationPoint IE_roleSelectionWindowVP() 
	{
		return vp("IE_roleSelectionWindow");
	}
	protected IFtVerificationPoint IE_roleSelectionWindowVP(TestObject anchor)
	{
		return vp("IE_roleSelectionWindow", anchor);
	}
	
	/**
	 * Locate and return the verification point IE_userDropDown_languageDropDown object in the SUT.
	 */
	protected IFtVerificationPoint IE_userDropDown_languageDropDownVP() 
	{
		return vp("IE_userDropDown_languageDropDown");
	}
	protected IFtVerificationPoint IE_userDropDown_languageDropDownVP(TestObject anchor)
	{
		return vp("IE_userDropDown_languageDropDown", anchor);
	}
	
	/**
	 * Locate and return the verification point userdropdown_THEME object in the SUT.
	 */
	protected IFtVerificationPoint userdropdown_THEMEVP() 
	{
		return vp("userdropdown_THEME");
	}
	protected IFtVerificationPoint userdropdown_THEMEVP(TestObject anchor)
	{
		return vp("userdropdown_THEME", anchor);
	}
	
	

	protected TS_995Helper()
	{
		setScriptName("TC_831_NetmailSearch.TS_995");
	}
	
}

