// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.utilities;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>HelperScript</b><br>
 * Generated     : <b>2013/09/05 5:30:29 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  September 05, 2013
 * @author Administrator
 */
public abstract class HelperScriptHelper extends utilities.MySuperHelper
{
	/**
	 * winRARClose: with default state.
	 *		.text : Close
	 * 		.class : .Pushbutton
	 * 		.name : Close
	 * 		.classIndex : 0
	 */
	protected GuiTestObject winRARClosebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("winRARClosebutton"));
	}
	/**
	 * winRARClose: with specific test context and state.
	 *		.text : Close
	 * 		.class : .Pushbutton
	 * 		.name : Close
	 * 		.classIndex : 0
	 */
	protected GuiTestObject winRARClosebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("winRARClosebutton"), anchor, flags);
	}
	
	/**
	 * winrarExtracting: with default state.
	 *		.class : RegularExpression(\#\d*)
	 * 		.processName : WinRAR.exe
	 */
	protected TopLevelSubitemTestObject winrarExtractingwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("winrarExtractingwindow"));
	}
	/**
	 * winrarExtracting: with specific test context and state.
	 *		.class : RegularExpression(\#\d*)
	 * 		.processName : WinRAR.exe
	 */
	protected TopLevelSubitemTestObject winrarExtractingwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("winrarExtractingwindow"), anchor, flags);
	}
	
	

	protected HelperScriptHelper()
	{
		setScriptName("utilities.HelperScript");
	}
	
}

