// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.RQM_RnD;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ReceivingExecutionVariable</b><br>
 * Generated     : <b>2015/04/20 9:46:15 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  April 20, 2015
 * @author Administrator
 */
public abstract class ReceivingExecutionVariableHelper extends utilities.MySuperHelper
{
	/**
	 * HtmlDialogButtonOpenWith: with default state.
	 *		.text : Open with
	 * 		.class : Html.DialogButton
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_htmlDialogButtonOpenWit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_htmlDialogButtonOpenWit"));
	}
	/**
	 * HtmlDialogButtonOpenWith: with specific test context and state.
	 *		.text : Open with
	 * 		.class : Html.DialogButton
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_htmlDialogButtonOpenWit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_htmlDialogButtonOpenWit"), anchor, flags);
	}
	
	/**
	 * HtmlDialogButtonSaveFile: with default state.
	 *		.text : Save File
	 * 		.class : Html.DialogButton
	 * 		.classIndex : 2
	 */
	protected GuiTestObject button_htmlDialogButtonSaveFil() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_htmlDialogButtonSaveFil"));
	}
	/**
	 * HtmlDialogButtonSaveFile: with specific test context and state.
	 *		.text : Save File
	 * 		.class : Html.DialogButton
	 * 		.classIndex : 2
	 */
	protected GuiTestObject button_htmlDialogButtonSaveFil(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_htmlDialogButtonSaveFil"), anchor, flags);
	}
	
	/**
	 * HtmlDialog: with default state.
	 *		.class : Html.Dialog
	 * 		.caption : Opening exportPST_Custom.zip
	 */
	protected TopLevelTestObject html_htmlDialog() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("html_htmlDialog"));
	}
	/**
	 * HtmlDialog: with specific test context and state.
	 *		.class : Html.Dialog
	 * 		.caption : Opening exportPST_Custom.zip
	 */
	protected TopLevelTestObject html_htmlDialog(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("html_htmlDialog"), anchor, flags);
	}
	
	/**
	 * List: with default state.
	 *		.class : .List
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject listlist() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("listlist"));
	}
	/**
	 * List: with specific test context and state.
	 *		.class : .List
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject listlist(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("listlist"), anchor, flags);
	}
	
	/**
	 * TDropDownEditButton: with default state.
	 *		.text : null
	 * 		.class : TDropDownEditButton
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject tDropDownEditButtonwindow() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("tDropDownEditButtonwindow"));
	}
	/**
	 * TDropDownEditButton: with specific test context and state.
	 *		.text : null
	 * 		.class : TDropDownEditButton
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject tDropDownEditButtonwindow(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("tDropDownEditButtonwindow"), anchor, flags);
	}
	
	

	protected ReceivingExecutionVariableHelper()
	{
		setScriptName("RQM_RnD.ReceivingExecutionVariable");
	}
	
}

