// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TC_441_ExportToPDF;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TS_975_SuperUserExportOnePDFPerItem</b><br>
 * Generated     : <b>2013/09/19 1:27:52 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  September 19, 2013
 * @author Administrator
 */
public abstract class TS_975_SuperUserExportOnePDFPerItemHelper extends utilities.MySuperHelper
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * DeleteExportedFilesbutton: with default state.
	 *		.text : Delete Exported Files
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_deleteExportedFilesbutt() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_deleteExportedFilesbutt"));
	}
	/**
	 * DeleteExportedFilesbutton: with specific test context and state.
	 *		.text : Delete Exported Files
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_deleteExportedFilesbutt(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_deleteExportedFilesbutt"), anchor, flags);
	}
	
	/**
	 * exportCasebutton: with default state.
	 *		.text : Export Case
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_exportCasebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_exportCasebutton"));
	}
	/**
	 * exportCasebutton: with specific test context and state.
	 *		.text : Export Case
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_exportCasebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_exportCasebutton"), anchor, flags);
	}
	
	/**
	 * Yesbutton: with default state.
	 *		.text : Yes
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_yesbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_yesbutton"));
	}
	/**
	 * Yesbutton: with specific test context and state.
	 *		.text : Yes
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_yesbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_yesbutton"), anchor, flags);
	}
	
	/**
	 * exportFilesList: with default state.
	 *		.className : x-grid3-body
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_exportFilesList() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportFilesList"));
	}
	/**
	 * exportFilesList: with specific test context and state.
	 *		.className : x-grid3-body
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_exportFilesList(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportFilesList"), anchor, flags);
	}
	
	/**
	 * exportList: with default state.
	 *		.className : x-grid3-body
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_exportList() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportList"));
	}
	/**
	 * exportList: with specific test context and state.
	 *		.className : x-grid3-body
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_exportList(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportList"), anchor, flags);
	}
	
	/**
	 * exportManagement: with default state.
	 *		.text : Export Management
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 */
	protected GuiTestObject link_exportManagement() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_exportManagement"));
	}
	/**
	 * exportManagement: with specific test context and state.
	 *		.text : Export Management
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 */
	protected GuiTestObject link_exportManagement(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_exportManagement"), anchor, flags);
	}
	
	/**
	 * noArchive_OK: with default state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject noArchive_OKbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("noArchive_OKbutton"));
	}
	/**
	 * noArchive_OK: with specific test context and state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject noArchive_OKbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("noArchive_OKbutton"), anchor, flags);
	}
	
	/**
	 * NoArchivesFound: with default state.
	 *		.class : .Statictext
	 * 		.name : No archives found
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject noArchivesFoundlabel() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("noArchivesFoundlabel"));
	}
	/**
	 * NoArchivesFound: with specific test context and state.
	 *		.class : .Statictext
	 * 		.name : No archives found
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject noArchivesFoundlabel(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("noArchivesFoundlabel"), anchor, flags);
	}
	
	/**
	 * messageHeader: with default state.
	 *		.class : Html.TABLE
	 */
	protected StatelessGuiSubitemTestObject table_messageHeader() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_messageHeader"));
	}
	/**
	 * messageHeader: with specific test context and state.
	 *		.class : Html.TABLE
	 */
	protected StatelessGuiSubitemTestObject table_messageHeader(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_messageHeader"), anchor, flags);
	}
	
	/**
	 * quickSearchField0: with default state.
	 *		type : text
	 * 		.id : quickSearchField0
	 * 		.class : Html.INPUT.text
	 * 		name : quickSearchField0
	 */
	protected TextGuiTestObject text_quickSearchField0() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_quickSearchField0"));
	}
	/**
	 * quickSearchField0: with specific test context and state.
	 *		type : text
	 * 		.id : quickSearchField0
	 * 		.class : Html.INPUT.text
	 * 		name : quickSearchField0
	 */
	protected TextGuiTestObject text_quickSearchField0(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_quickSearchField0"), anchor, flags);
	}
	
	/**
	 * winRARClose: with default state.
	 *		.text : Close
	 * 		.class : .Pushbutton
	 * 		.name : Close
	 * 		.classIndex : 0
	 */
	protected GuiTestObject winRARClosebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("winRARClosebutton"));
	}
	/**
	 * winRARClose: with specific test context and state.
	 *		.text : Close
	 * 		.class : .Pushbutton
	 * 		.name : Close
	 * 		.classIndex : 0
	 */
	protected GuiTestObject winRARClosebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("winRARClosebutton"), anchor, flags);
	}
	
	/**
	 * winrarExtracting: with default state.
	 *		.class : RegularExpression(\#\d*)
	 * 		.processName : WinRAR.exe
	 */
	protected TopLevelSubitemTestObject winrarExtractingwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("winrarExtractingwindow"));
	}
	/**
	 * winrarExtracting: with specific test context and state.
	 *		.class : RegularExpression(\#\d*)
	 * 		.processName : WinRAR.exe
	 */
	protected TopLevelSubitemTestObject winrarExtractingwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("winrarExtractingwindow"), anchor, flags);
	}
	
	

	protected TS_975_SuperUserExportOnePDFPerItemHelper()
	{
		setScriptName("TC_441_ExportToPDF.TS_975_SuperUserExportOnePDFPerItem");
	}
	
}

