// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TC_446_ExportPST;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TS_120_FailureToSavePST</b><br>
 * Generated     : <b>2013/08/27 4:11:59 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  August 27, 2013
 * @author Administrator
 */
public abstract class TS_120_FailureToSavePSTHelper extends utilities.MySuperHelper
{
	/**
	 * AddressBandRoot: with default state.
	 *		.text : null
	 * 		.class : Address Band Root
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject addressBandRootwindow() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("addressBandRootwindow"));
	}
	/**
	 * AddressBandRoot: with specific test context and state.
	 *		.text : null
	 * 		.class : Address Band Root
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject addressBandRootwindow(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("addressBandRootwindow"), anchor, flags);
	}
	
	/**
	 * AddressCUsersAdministratorDownloads: with default state.
	 *		.text : Address: C:\Users\Administrator\Downloads
	 * 		.class : ToolbarWindow32
	 * 		.name : Address: C:\Users\Administrator\Downloads
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject addressCUsersAdministratorDown() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("addressCUsersAdministratorDown"));
	}
	/**
	 * AddressCUsersAdministratorDownloads: with specific test context and state.
	 *		.text : Address: C:\Users\Administrator\Downloads
	 * 		.class : ToolbarWindow32
	 * 		.name : Address: C:\Users\Administrator\Downloads
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject addressCUsersAdministratorDown(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("addressCUsersAdministratorDown"), anchor, flags);
	}
	
	/**
	 * BreadcrumbParent: with default state.
	 *		.text : null
	 * 		.class : Breadcrumb Parent
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject breadcrumbParentwindow() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("breadcrumbParentwindow"));
	}
	/**
	 * BreadcrumbParent: with specific test context and state.
	 *		.text : null
	 * 		.class : Breadcrumb Parent
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject breadcrumbParentwindow(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("breadcrumbParentwindow"), anchor, flags);
	}
	
	/**
	 * ExportCasebutton: with default state.
	 *		.text : Export Case
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_exportCasebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_exportCasebutton"));
	}
	/**
	 * ExportCasebutton: with specific test context and state.
	 *		.text : Export Case
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_exportCasebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_exportCasebutton"), anchor, flags);
	}
	
	/**
	 * exportFileList: with default state.
	 *		.className : x-grid3-body
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_exportFileList() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportFileList"));
	}
	/**
	 * exportFileList: with specific test context and state.
	 *		.className : x-grid3-body
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_exportFileList(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportFileList"), anchor, flags);
	}
	
	/**
	 * exportList: with default state.
	 *		.className : x-grid3-body
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_exportList() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportList"));
	}
	/**
	 * exportList: with specific test context and state.
	 *		.className : x-grid3-body
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_exportList(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportList"), anchor, flags);
	}
	
	/**
	 * exportManagement: with default state.
	 *		.text : Export Management
	 * 		.href : http://10.10.24.80:8888/index.html#
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class : x-menu-item
	 */
	protected GuiTestObject link_exportManagement() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_exportManagement"));
	}
	/**
	 * exportManagement: with specific test context and state.
	 *		.text : Export Management
	 * 		.href : http://10.10.24.80:8888/index.html#
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class : x-menu-item
	 */
	protected GuiTestObject link_exportManagement(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_exportManagement"), anchor, flags);
	}
	
	/**
	 * readOnlyClose: with default state.
	 *		.text : Close
	 * 		.class : .Pushbutton
	 * 		.name : Close
	 * 		.classIndex : 0
	 */
	protected GuiTestObject readOnlyClosebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("readOnlyClosebutton"));
	}
	/**
	 * readOnlyClose: with specific test context and state.
	 *		.text : Close
	 * 		.class : .Pushbutton
	 * 		.name : Close
	 * 		.classIndex : 0
	 */
	protected GuiTestObject readOnlyClosebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("readOnlyClosebutton"), anchor, flags);
	}
	
	/**
	 * readOnlyContinue: with default state.
	 *		.text : Continue
	 * 		.class : .Pushbutton
	 * 		.name : Continue
	 * 		.classIndex : 0
	 */
	protected GuiTestObject readOnlyContinuebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("readOnlyContinuebutton"));
	}
	/**
	 * readOnlyContinue: with specific test context and state.
	 *		.text : Continue
	 * 		.class : .Pushbutton
	 * 		.name : Continue
	 * 		.classIndex : 0
	 */
	protected GuiTestObject readOnlyContinuebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("readOnlyContinuebutton"), anchor, flags);
	}
	
	/**
	 * saveAsCancel: with default state.
	 *		.text : Cancel
	 * 		.class : .Pushbutton
	 * 		.name : Cancel
	 * 		.classIndex : 0
	 */
	protected GuiTestObject saveAsCancelbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("saveAsCancelbutton"));
	}
	/**
	 * saveAsCancel: with specific test context and state.
	 *		.text : Cancel
	 * 		.class : .Pushbutton
	 * 		.name : Cancel
	 * 		.classIndex : 0
	 */
	protected GuiTestObject saveAsCancelbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("saveAsCancelbutton"), anchor, flags);
	}
	
	/**
	 * SaveAs: with default state.
	 *		.text : Save as
	 * 		.class : .Menuitem
	 * 		.name : Save as
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject saveAsmenuItem() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("saveAsmenuItem"));
	}
	/**
	 * SaveAs: with specific test context and state.
	 *		.text : Save as
	 * 		.class : .Menuitem
	 * 		.name : Save as
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject saveAsmenuItem(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("saveAsmenuItem"), anchor, flags);
	}
	
	/**
	 * SaveAs: with default state.
	 *		.text : Save As
	 * 		.class : RegularExpression(\#\d*)
	 * 		.processName : iexplore.exe
	 * 		.name : Save As
	 */
	protected TopLevelSubitemTestObject saveAswindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("saveAswindow"));
	}
	/**
	 * SaveAs: with specific test context and state.
	 *		.text : Save As
	 * 		.class : RegularExpression(\#\d*)
	 * 		.processName : iexplore.exe
	 * 		.name : Save As
	 */
	protected TopLevelSubitemTestObject saveAswindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("saveAswindow"), anchor, flags);
	}
	
	

	protected TS_120_FailureToSavePSTHelper()
	{
		setScriptName("TC_446_ExportPST.TS_120_FailureToSavePST");
	}
	
}

