// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TC_446_ExportPST;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TS_979_ExportPST</b><br>
 * Generated     : <b>2013/09/06 4:03:39 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  September 06, 2013
 * @author Administrator
 */
public abstract class TS_979_ExportPSTHelper extends utilities.MySuperHelper
{
	/**
	 * DeleteExportedFilesbutton: with default state.
	 *		.text : Delete Exported Files
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_deleteExportedFilesbutt() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_deleteExportedFilesbutt"));
	}
	/**
	 * DeleteExportedFilesbutton: with specific test context and state.
	 *		.text : Delete Exported Files
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_deleteExportedFilesbutt(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_deleteExportedFilesbutt"), anchor, flags);
	}
	
	/**
	 * ExportCasebutton: with default state.
	 *		.text : Export Case
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_exportCasebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_exportCasebutton"));
	}
	/**
	 * ExportCasebutton: with specific test context and state.
	 *		.text : Export Case
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_exportCasebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_exportCasebutton"), anchor, flags);
	}
	
	/**
	 * Yesbutton: with default state.
	 *		.text : Yes
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_yesbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_yesbutton"));
	}
	/**
	 * Yesbutton: with specific test context and state.
	 *		.text : Yes
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_yesbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_yesbutton"), anchor, flags);
	}
	
	/**
	 * exportFilesList: with default state.
	 *		.className : x-grid3-body
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_exportFilesList() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportFilesList"));
	}
	/**
	 * exportFilesList: with specific test context and state.
	 *		.className : x-grid3-body
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_exportFilesList(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportFilesList"), anchor, flags);
	}
	
	/**
	 * exportList: with default state.
	 *		.className : x-grid3-body
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_exportList() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportList"));
	}
	/**
	 * exportList: with specific test context and state.
	 *		.className : x-grid3-body
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_exportList(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportList"), anchor, flags);
	}
	
	/**
	 * exportManagement: with default state.
	 *		.text : Export Management
	 * 		.title : 
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 */
	protected GuiTestObject link_exportManagement() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_exportManagement"));
	}
	/**
	 * exportManagement: with specific test context and state.
	 *		.text : Export Management
	 * 		.title : 
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 */
	protected GuiTestObject link_exportManagement(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_exportManagement"), anchor, flags);
	}
	
	

	protected TS_979_ExportPSTHelper()
	{
		setScriptName("TC_446_ExportPST.TS_979_ExportPST");
	}
	
}

