// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.NetmailSearch_PrintAndExport;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Export_SuperUser</b><br>
 * Generated     : <b>2014/08/05 11:27:57 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  August 05, 2014
 * @author Administrator
 */
public abstract class Export_SuperUserHelper extends utilities.MySuperHelper
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * DeleteExportAfterClicked: with default state.
	 *		.text : Delete Exported Files
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_deleteExportAfterClicke() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_deleteExportAfterClicke"));
	}
	/**
	 * DeleteExportAfterClicked: with specific test context and state.
	 *		.text : Delete Exported Files
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_deleteExportAfterClicke(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_deleteExportAfterClicke"), anchor, flags);
	}
	
	/**
	 * DeleteExportedFilesbutton: with default state.
	 *		.text : Delete Exported Files
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		.contentText : Delete Exported Files
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_deleteExportedFilesbutt() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_deleteExportedFilesbutt"));
	}
	/**
	 * DeleteExportedFilesbutton: with specific test context and state.
	 *		.text : Delete Exported Files
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		.contentText : Delete Exported Files
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_deleteExportedFilesbutt(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_deleteExportedFilesbutt"), anchor, flags);
	}
	
	/**
	 * ExportCasebutton: with default state.
	 *		.text : Export Case
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_exportCasebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_exportCasebutton"));
	}
	/**
	 * ExportCasebutton: with specific test context and state.
	 *		.text : Export Case
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_exportCasebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_exportCasebutton"), anchor, flags);
	}
	
	/**
	 * Finishbutton: with default state.
	 *		.text : Finish
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_finishbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_finishbutton"));
	}
	/**
	 * Finishbutton: with specific test context and state.
	 *		.text : Finish
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_finishbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_finishbutton"), anchor, flags);
	}
	
	/**
	 * HideThisReminderNextTimebutton: with default state.
	 *		.text : Hide this reminder next time
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_hideThisReminderNextTim() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_hideThisReminderNextTim"));
	}
	/**
	 * HideThisReminderNextTimebutton: with specific test context and state.
	 *		.text : Hide this reminder next time
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_hideThisReminderNextTim(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_hideThisReminderNextTim"), anchor, flags);
	}
	
	/**
	 * netmailLite_ExportCasebutton: with default state.
	 *		.text : Export Case
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_netmailLite_ExportCaseb() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_netmailLite_ExportCaseb"));
	}
	/**
	 * netmailLite_ExportCasebutton: with specific test context and state.
	 *		.text : Export Case
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_netmailLite_ExportCaseb(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_netmailLite_ExportCaseb"), anchor, flags);
	}
	
	/**
	 * netmailLite_ExportCasebutton_After: with default state.
	 *		.text : Export Case
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_netmailLite_ExportCaseb2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_netmailLite_ExportCaseb2"));
	}
	/**
	 * netmailLite_ExportCasebutton_After: with specific test context and state.
	 *		.text : Export Case
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_netmailLite_ExportCaseb2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_netmailLite_ExportCaseb2"), anchor, flags);
	}
	
	/**
	 * NextButton: with default state.
	 *		.text : Next »
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_nextButton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_nextButton"));
	}
	/**
	 * NextButton: with specific test context and state.
	 *		.text : Next »
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_nextButton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_nextButton"), anchor, flags);
	}
	
	/**
	 * reminder_OKbutton: with default state.
	 *		.text : OK
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_reminder_OKbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_reminder_OKbutton"));
	}
	/**
	 * reminder_OKbutton: with specific test context and state.
	 *		.text : OK
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_reminder_OKbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_reminder_OKbutton"), anchor, flags);
	}
	
	/**
	 * Yes: with default state.
	 *		.text : Yes
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_yesbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_yesbutton"));
	}
	/**
	 * Yes: with specific test context and state.
	 *		.text : Yes
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_yesbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_yesbutton"), anchor, flags);
	}
	
	/**
	 * step5_send_mailstep5_send_mail: with default state.
	 *		type : checkbox
	 * 		.id : step5_send_mail
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		name : step5_send_mail
	 * 		value : step5_send_mail
	 * 		class :  x-form-checkbox x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_step5_send_mailstep5_() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_step5_send_mailstep5_"));
	}
	/**
	 * step5_send_mailstep5_send_mail: with specific test context and state.
	 *		type : checkbox
	 * 		.id : step5_send_mail
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		name : step5_send_mail
	 * 		value : step5_send_mail
	 * 		class :  x-form-checkbox x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_step5_send_mailstep5_(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_step5_send_mailstep5_"), anchor, flags);
	}
	
	/**
	 * step5_with_passwordstep5_with_password: with default state.
	 *		type : checkbox
	 * 		.id : step5_with_password
	 * 		.class : Html.INPUT.checkbox
	 * 		name : step5_with_password
	 * 		value : step5_with_password
	 * 		class :  x-form-checkbox x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_step5_with_passwordst() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_step5_with_passwordst"));
	}
	/**
	 * step5_with_passwordstep5_with_password: with specific test context and state.
	 *		type : checkbox
	 * 		.id : step5_with_password
	 * 		.class : Html.INPUT.checkbox
	 * 		name : step5_with_password
	 * 		value : step5_with_password
	 * 		class :  x-form-checkbox x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_step5_with_passwordst(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_step5_with_passwordst"), anchor, flags);
	}
	
	/**
	 * additionalOptionContainer: with default state.
	 *		.className : x-panel-body x-panel-body-noheader
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_additionalOptionContainer() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_additionalOptionContainer"));
	}
	/**
	 * additionalOptionContainer: with specific test context and state.
	 *		.className : x-panel-body x-panel-body-noheader
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_additionalOptionContainer(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_additionalOptionContainer"), anchor, flags);
	}
	
	/**
	 * closeExportWindow: with default state.
	 *		.className : x-tool x-tool-close
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_closeExportWindow() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_closeExportWindow"));
	}
	/**
	 * closeExportWindow: with specific test context and state.
	 *		.className : x-tool x-tool-close
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_closeExportWindow(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_closeExportWindow"), anchor, flags);
	}
	
	/**
	 * exportFilesList: with default state.
	 *		.className : x-grid3-body
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_exportFilesList() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportFilesList"));
	}
	/**
	 * exportFilesList: with specific test context and state.
	 *		.className : x-grid3-body
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_exportFilesList(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportFilesList"), anchor, flags);
	}
	
	/**
	 * exportList: with default state.
	 *		.className : x-grid3-body
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_exportList() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportList"));
	}
	/**
	 * exportList: with specific test context and state.
	 *		.className : x-grid3-body
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_exportList(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportList"), anchor, flags);
	}
	
	/**
	 * exportStatusWindow: with default state.
	 *		id : exportStatusWindow
	 * 		.id : exportStatusWindow
	 * 		.className : x-window x-window-noborder x-window-plain x-resizable-pinned
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_exportStatusWindow() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportStatusWindow"));
	}
	/**
	 * exportStatusWindow: with specific test context and state.
	 *		id : exportStatusWindow
	 * 		.id : exportStatusWindow
	 * 		.className : x-window x-window-noborder x-window-plain x-resizable-pinned
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_exportStatusWindow(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportStatusWindow"), anchor, flags);
	}
	
	/**
	 * exportWindow: with default state.
	 *		.id : exportWindow
	 * 		.className :  x-window x-window-noborder x-window-plain
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_exportWindow() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportWindow"));
	}
	/**
	 * exportWindow: with specific test context and state.
	 *		.id : exportWindow
	 * 		.className :  x-window x-window-noborder x-window-plain
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_exportWindow(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_exportWindow"), anchor, flags);
	}
	
	/**
	 * extGen10360: with default state.
	 *		.className : x-panel-body x-panel-body-noheader
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_extGen10360() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen10360"));
	}
	/**
	 * extGen10360: with specific test context and state.
	 *		.className : x-panel-body x-panel-body-noheader
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_extGen10360(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen10360"), anchor, flags);
	}
	
	/**
	 * reminderMessage: with default state.
	 *		.text : When exporting to Portable Netmail Search with Audit Files selected, Comments an ...
	 * 		.className : ext-mb-text
	 * 		.title : 
	 * 		.class : Html.SPAN
	 */
	protected GuiTestObject html_reminderMessage() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_reminderMessage"));
	}
	/**
	 * reminderMessage: with specific test context and state.
	 *		.text : When exporting to Portable Netmail Search with Audit Files selected, Comments an ...
	 * 		.className : ext-mb-text
	 * 		.title : 
	 * 		.class : Html.SPAN
	 */
	protected GuiTestObject html_reminderMessage(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_reminderMessage"), anchor, flags);
	}
	
	/**
	 * step1_list_search_tabs: with default state.
	 *		.id : step1_list_search_tabs
	 * 		.className : x-panel x-panel-noborder x-grid-panel
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_step1_list_search_tabs() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_step1_list_search_tabs"));
	}
	/**
	 * step1_list_search_tabs: with specific test context and state.
	 *		.id : step1_list_search_tabs
	 * 		.className : x-panel x-panel-noborder x-grid-panel
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_step1_list_search_tabs(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_step1_list_search_tabs"), anchor, flags);
	}
	
	/**
	 * typeExportContainer: with default state.
	 *		.className : x-panel-body x-panel-body-noheader
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_typeExportContainer() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_typeExportContainer"));
	}
	/**
	 * typeExportContainer: with specific test context and state.
	 *		.className : x-panel-body x-panel-body-noheader
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_typeExportContainer(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_typeExportContainer"), anchor, flags);
	}
	
	/**
	 * exportManage: with default state.
	 *		.text : Export Management
	 * 		.title : 
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 */
	protected GuiTestObject link_exportManage() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_exportManage"));
	}
	/**
	 * exportManage: with specific test context and state.
	 *		.text : Export Management
	 * 		.title : 
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 */
	protected GuiTestObject link_exportManage(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_exportManage"), anchor, flags);
	}
	
	/**
	 * newExport: with default state.
	 *		.text : New Export
	 * 		.href : http://10.10.24.80:8888/index.html#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_newExport() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_newExport"));
	}
	/**
	 * newExport: with specific test context and state.
	 *		.text : New Export
	 * 		.href : http://10.10.24.80:8888/index.html#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_newExport(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_newExport"), anchor, flags);
	}
	
	/**
	 * include_tabsevery_tabs: with default state.
	 *		.text : 
	 * 		.id : step1_include_all_tabs
	 * 		.type : radio
	 * 		.value : every_tabs
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : include_tabs
	 * 		.classIndex : 0
	 * 		class :  x-form-radio x-form-field
	 */
	protected ToggleGUITestObject radioButton_include_tabsevery_() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_include_tabsevery_"));
	}
	/**
	 * include_tabsevery_tabs: with specific test context and state.
	 *		.text : 
	 * 		.id : step1_include_all_tabs
	 * 		.type : radio
	 * 		.value : every_tabs
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : include_tabs
	 * 		.classIndex : 0
	 * 		class :  x-form-radio x-form-field
	 */
	protected ToggleGUITestObject radioButton_include_tabsevery_(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_include_tabsevery_"), anchor, flags);
	}
	
	/**
	 * include_tabsselected_tabs: with default state.
	 *		.text : 
	 * 		.type : radio
	 * 		.value : selected_tabs
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : include_tabs
	 * 		.classIndex : 0
	 * 		class :  x-form-radio x-form-field
	 */
	protected ToggleGUITestObject radioButton_include_tabsselect() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_include_tabsselect"));
	}
	/**
	 * include_tabsselected_tabs: with specific test context and state.
	 *		.text : 
	 * 		.type : radio
	 * 		.value : selected_tabs
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : include_tabs
	 * 		.classIndex : 0
	 * 		class :  x-form-radio x-form-field
	 */
	protected ToggleGUITestObject radioButton_include_tabsselect(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_include_tabsselect"), anchor, flags);
	}
	
	/**
	 * step2_everMail: with default state.
	 *		.text : 
	 * 		.id : step2_include_all_mails
	 * 		.type : radio
	 * 		.value : every_mails
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step2_include_mails
	 * 		.classIndex : 0
	 * 		class :  x-form-radio x-form-field
	 */
	protected ToggleGUITestObject radioButton_step2_everMail() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step2_everMail"));
	}
	/**
	 * step2_everMail: with specific test context and state.
	 *		.text : 
	 * 		.id : step2_include_all_mails
	 * 		.type : radio
	 * 		.value : every_mails
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step2_include_mails
	 * 		.classIndex : 0
	 * 		class :  x-form-radio x-form-field
	 */
	protected ToggleGUITestObject radioButton_step2_everMail(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step2_everMail"), anchor, flags);
	}
	
	/**
	 * step2_selectedMails: with default state.
	 *		.text : 
	 * 		.id : step2_include_selected_mails
	 * 		.type : radio
	 * 		.value : selected_mails
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step2_include_mails
	 * 		.classIndex : 0
	 * 		class :  x-form-radio x-form-field
	 */
	protected ToggleGUITestObject radioButton_step2_selectedMail() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step2_selectedMail"));
	}
	/**
	 * step2_selectedMails: with specific test context and state.
	 *		.text : 
	 * 		.id : step2_include_selected_mails
	 * 		.type : radio
	 * 		.value : selected_mails
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step2_include_mails
	 * 		.classIndex : 0
	 * 		class :  x-form-radio x-form-field
	 */
	protected ToggleGUITestObject radioButton_step2_selectedMail(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step2_selectedMail"), anchor, flags);
	}
	
	/**
	 * step3_ONE_PDF: with default state.
	 *		.text : 
	 * 		.id : step3_one_pdf
	 * 		.type : radio
	 * 		.value : one_pdf
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step3_export_type
	 * 		.classIndex : 0
	 * 		class :  x-form-radio x-form-field
	 */
	protected ToggleGUITestObject radioButton_step3_ONE_PDF() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step3_ONE_PDF"));
	}
	/**
	 * step3_ONE_PDF: with specific test context and state.
	 *		.text : 
	 * 		.id : step3_one_pdf
	 * 		.type : radio
	 * 		.value : one_pdf
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step3_export_type
	 * 		.classIndex : 0
	 * 		class :  x-form-radio x-form-field
	 */
	protected ToggleGUITestObject radioButton_step3_ONE_PDF(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step3_ONE_PDF"), anchor, flags);
	}
	
	/**
	 * step3_PDF_PER_ITEM: with default state.
	 *		.text : 
	 * 		.id : step3_multiple_pdf
	 * 		.type : radio
	 * 		.value : multiple_pdf
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step3_export_type
	 * 		.classIndex : 0
	 * 		class :  x-form-radio x-form-field
	 */
	protected ToggleGUITestObject radioButton_step3_PDF_PER_ITEM() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step3_PDF_PER_ITEM"));
	}
	/**
	 * step3_PDF_PER_ITEM: with specific test context and state.
	 *		.text : 
	 * 		.id : step3_multiple_pdf
	 * 		.type : radio
	 * 		.value : multiple_pdf
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step3_export_type
	 * 		.classIndex : 0
	 * 		class :  x-form-radio x-form-field
	 */
	protected ToggleGUITestObject radioButton_step3_PDF_PER_ITEM(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step3_PDF_PER_ITEM"), anchor, flags);
	}
	
	/**
	 * step3_PST: with default state.
	 *		.text : 
	 * 		.id : step3_pst
	 * 		.type : radio
	 * 		.value : pst
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step3_export_type
	 * 		class :  x-form-radio x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_step3_PST() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step3_PST"));
	}
	/**
	 * step3_PST: with specific test context and state.
	 *		.text : 
	 * 		.id : step3_pst
	 * 		.type : radio
	 * 		.value : pst
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step3_export_type
	 * 		class :  x-form-radio x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_step3_PST(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step3_PST"), anchor, flags);
	}
	
	/**
	 * step3_Portable: with default state.
	 *		.text : 
	 * 		.id : step3_searchable_xml
	 * 		.type : radio
	 * 		.value : searchable_xml
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step3_export_type
	 * 		class :  x-form-radio x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_step3_Portable() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step3_Portable"));
	}
	/**
	 * step3_Portable: with specific test context and state.
	 *		.text : 
	 * 		.id : step3_searchable_xml
	 * 		.type : radio
	 * 		.value : searchable_xml
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step3_export_type
	 * 		class :  x-form-radio x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_step3_Portable(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step3_Portable"), anchor, flags);
	}
	
	/**
	 * step5_cd_iso: with default state.
	 *		.text : 
	 * 		.id : step5_cd_iso
	 * 		.type : radio
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.browserName : MS Internet Explorer
	 * 		.name : step5_package_type
	 * 		class :  x-form-radio x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_step5_cd_iso() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step5_cd_iso"));
	}
	/**
	 * step5_cd_iso: with specific test context and state.
	 *		.text : 
	 * 		.id : step5_cd_iso
	 * 		.type : radio
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.browserName : MS Internet Explorer
	 * 		.name : step5_package_type
	 * 		class :  x-form-radio x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_step5_cd_iso(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step5_cd_iso"), anchor, flags);
	}
	
	/**
	 * step5_dvd_iso: with default state.
	 *		.text : 
	 * 		.id : step5_dvd_iso
	 * 		.type : radio
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.browserName : MS Internet Explorer
	 * 		.name : step5_package_type
	 * 		class :  x-form-radio x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_step5_dvd_iso() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step5_dvd_iso"));
	}
	/**
	 * step5_dvd_iso: with specific test context and state.
	 *		.text : 
	 * 		.id : step5_dvd_iso
	 * 		.type : radio
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.browserName : MS Internet Explorer
	 * 		.name : step5_package_type
	 * 		class :  x-form-radio x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_step5_dvd_iso(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step5_dvd_iso"), anchor, flags);
	}
	
	/**
	 * step5_package_CD: with default state.
	 *		.text : 
	 * 		.id : step5_cd
	 * 		.type : radio
	 * 		.value : 650MB
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step5_package_type
	 * 		class :  x-form-radio x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_step5_package_CD() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step5_package_CD"));
	}
	/**
	 * step5_package_CD: with specific test context and state.
	 *		.text : 
	 * 		.id : step5_cd
	 * 		.type : radio
	 * 		.value : 650MB
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step5_package_type
	 * 		class :  x-form-radio x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_step5_package_CD(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step5_package_CD"), anchor, flags);
	}
	
	/**
	 * step5_package_Custom: with default state.
	 *		.text : 
	 * 		.id : step5_custom
	 * 		.type : radio
	 * 		.value : custom
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step5_package_type
	 * 		class :  x-form-radio x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_step5_package_Cust() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step5_package_Cust"));
	}
	/**
	 * step5_package_Custom: with specific test context and state.
	 *		.text : 
	 * 		.id : step5_custom
	 * 		.type : radio
	 * 		.value : custom
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step5_package_type
	 * 		class :  x-form-radio x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_step5_package_Cust(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step5_package_Cust"), anchor, flags);
	}
	
	/**
	 * step5_package_DVD: with default state.
	 *		.text : 
	 * 		.id : step5_dvd
	 * 		.type : radio
	 * 		.value : 4.7GB
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step5_package_type
	 * 		class :  x-form-radio x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_step5_package_DVD() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step5_package_DVD"));
	}
	/**
	 * step5_package_DVD: with specific test context and state.
	 *		.text : 
	 * 		.id : step5_dvd
	 * 		.type : radio
	 * 		.value : 4.7GB
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step5_package_type
	 * 		class :  x-form-radio x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_step5_package_DVD(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step5_package_DVD"), anchor, flags);
	}
	
	/**
	 * step5_package_SinglePackage: with default state.
	 *		.text : 
	 * 		.id : step5_none
	 * 		.type : radio
	 * 		.value : -1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step5_package_type
	 * 		class :  x-form-radio x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_step5_package_Sing() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step5_package_Sing"));
	}
	/**
	 * step5_package_SinglePackage: with specific test context and state.
	 *		.text : 
	 * 		.id : step5_none
	 * 		.type : radio
	 * 		.value : -1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : step5_package_type
	 * 		class :  x-form-radio x-form-field
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_step5_package_Sing(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_step5_package_Sing"), anchor, flags);
	}
	
	/**
	 * cardFinish: with default state.
	 *		.id : card-finish
	 * 		.class : Html.TABLE
	 */
	protected StatelessGuiSubitemTestObject table_cardFinish() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_cardFinish"));
	}
	/**
	 * cardFinish: with specific test context and state.
	 *		.id : card-finish
	 * 		.class : Html.TABLE
	 */
	protected StatelessGuiSubitemTestObject table_cardFinish(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_cardFinish"), anchor, flags);
	}
	
	/**
	 * netmailLite_exportButton: with default state.
	 *		.id : exportButton
	 * 		.class : Html.TABLE
	 */
	protected StatelessGuiSubitemTestObject table_netmailLite_exportButton() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_netmailLite_exportButton"));
	}
	/**
	 * netmailLite_exportButton: with specific test context and state.
	 *		.id : exportButton
	 * 		.class : Html.TABLE
	 */
	protected StatelessGuiSubitemTestObject table_netmailLite_exportButton(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_netmailLite_exportButton"), anchor, flags);
	}
	
	/**
	 * step5_custom_size: with default state.
	 *		.text : 
	 * 		type : text
	 * 		.id : step5_custom_size
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		name : step5_custom_size
	 * 		class : x-form-text x-form-field
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_step5_custom_size() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_step5_custom_size"));
	}
	/**
	 * step5_custom_size: with specific test context and state.
	 *		.text : 
	 * 		type : text
	 * 		.id : step5_custom_size
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		name : step5_custom_size
	 * 		class : x-form-text x-form-field
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_step5_custom_size(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_step5_custom_size"), anchor, flags);
	}
	
	/**
	 * step5_export_email: with default state.
	 *		.text : 
	 * 		type : text
	 * 		.id : step5_export_email
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		name : step5_export_email
	 * 		class : x-form-text x-form-field
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_step5_export_email() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_step5_export_email"));
	}
	/**
	 * step5_export_email: with specific test context and state.
	 *		.text : 
	 * 		type : text
	 * 		.id : step5_export_email
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		name : step5_export_email
	 * 		class : x-form-text x-form-field
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_step5_export_email(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_step5_export_email"), anchor, flags);
	}
	
	/**
	 * step5_export_name: with default state.
	 *		.text : 
	 * 		type : text
	 * 		.id : step5_export_name
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		name : step5_export_name
	 * 		class : x-form-text x-form-field
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_step5_export_name() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_step5_export_name"));
	}
	/**
	 * step5_export_name: with specific test context and state.
	 *		.text : 
	 * 		type : text
	 * 		.id : step5_export_name
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		name : step5_export_name
	 * 		class : x-form-text x-form-field
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_step5_export_name(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_step5_export_name"), anchor, flags);
	}
	
	/**
	 * step5_password1: with default state.
	 *		.id : step5_password1
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : step5_password1
	 * 		class : x-form-text x-form-field
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_step5_password1() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_step5_password1"));
	}
	/**
	 * step5_password1: with specific test context and state.
	 *		.id : step5_password1
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : step5_password1
	 * 		class : x-form-text x-form-field
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_step5_password1(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_step5_password1"), anchor, flags);
	}
	
	/**
	 * step5_password2: with default state.
	 *		.id : step5_password2
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : step5_password2
	 * 		class : x-form-text x-form-field
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_step5_password2() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_step5_password2"));
	}
	/**
	 * step5_password2: with specific test context and state.
	 *		.id : step5_password2
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : step5_password2
	 * 		class : x-form-text x-form-field
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_step5_password2(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_step5_password2"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point onePDFWarning object in the SUT.
	 */
	protected IFtVerificationPoint onePDFWarningVP() 
	{
		return vp("onePDFWarning");
	}
	protected IFtVerificationPoint onePDFWarningVP(TestObject anchor)
	{
		return vp("onePDFWarning", anchor);
	}
	
	

	protected Export_SuperUserHelper()
	{
		setScriptName("NetmailSearch_PrintAndExport.Export_SuperUser");
	}
	
}

