// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TestCases.TC_General;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TS_MessageRecipientFields</b><br>
 * Generated     : <b>2014/07/21 5:04:39 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  July 21, 2014
 * @author Administrator
 */
public abstract class TS_MessageRecipientFieldsHelper extends utilities.MySuperHelper
{
	/**
	 * closeMessage: with default state.
	 *		.className : x-tool x-tool-close
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_closeMessage() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_closeMessage"));
	}
	/**
	 * closeMessage: with specific test context and state.
	 *		.className : x-tool x-tool-close
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_closeMessage(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_closeMessage"), anchor, flags);
	}
	
	/**
	 * propertiesList: with default state.
	 *		.class : Html.UL
	 * 		class : x-tree-root-ct x-tree-no-lines
	 */
	protected GuiTestObject html_propertiesList() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_propertiesList"));
	}
	/**
	 * propertiesList: with specific test context and state.
	 *		.class : Html.UL
	 * 		class : x-tree-root-ct x-tree-no-lines
	 */
	protected GuiTestObject html_propertiesList(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_propertiesList"), anchor, flags);
	}
	
	/**
	 * previewTab: with default state.
	 *		.text : Preview
	 * 		.href : http://10.1.30.64:8888/index.html#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 * 		class : x-tab-right
	 */
	protected GuiTestObject link_previewTab() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_previewTab"));
	}
	/**
	 * previewTab: with specific test context and state.
	 *		.text : Preview
	 * 		.href : http://10.1.30.64:8888/index.html#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 * 		class : x-tab-right
	 */
	protected GuiTestObject link_previewTab(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_previewTab"), anchor, flags);
	}
	
	/**
	 * propertiesTab: with default state.
	 *		.text : Properties
	 * 		.href : http://10.1.30.64:8888/index.html#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 * 		class : x-tab-right
	 */
	protected GuiTestObject link_propertiesTab() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_propertiesTab"));
	}
	/**
	 * propertiesTab: with specific test context and state.
	 *		.text : Properties
	 * 		.href : http://10.1.30.64:8888/index.html#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 * 		class : x-tab-right
	 */
	protected GuiTestObject link_propertiesTab(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_propertiesTab"), anchor, flags);
	}
	
	/**
	 * bc: with default state.
	 *		.class : Html.INPUT.text
	 * 		name : bc
	 * 		.name : bc
	 */
	protected TextGuiTestObject text_bc() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_bc"));
	}
	/**
	 * bc: with specific test context and state.
	 *		.class : Html.INPUT.text
	 * 		name : bc
	 * 		.name : bc
	 */
	protected TextGuiTestObject text_bc(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_bc"), anchor, flags);
	}
	
	/**
	 * cc: with default state.
	 *		.class : Html.INPUT.text
	 * 		name : cc
	 * 		.name : cc
	 */
	protected TextGuiTestObject text_cc() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_cc"));
	}
	/**
	 * cc: with specific test context and state.
	 *		.class : Html.INPUT.text
	 * 		name : cc
	 * 		.name : cc
	 */
	protected TextGuiTestObject text_cc(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_cc"), anchor, flags);
	}
	
	/**
	 * to: with default state.
	 *		.class : Html.INPUT.text
	 * 		name : to
	 */
	protected TextGuiTestObject text_to() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_to"));
	}
	/**
	 * to: with specific test context and state.
	 *		.class : Html.INPUT.text
	 * 		name : to
	 */
	protected TextGuiTestObject text_to(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_to"), anchor, flags);
	}
	
	

	protected TS_MessageRecipientFieldsHelper()
	{
		setScriptName("TestCases.TC_General.TS_MessageRecipientFields");
	}
	
}

