// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.NetmailSearch_General;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Common</b><br>
 * Generated     : <b>2014/07/29 11:04:06 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  July 29, 2014
 * @author Administrator
 */
public abstract class CommonHelper extends utilities.MySuperHelper
{
	/**
	 * firstPage: with default state.
	 *		type : button
	 * 		.className : RegularExpression(.*x-btn-text x-tbar-page-first.*)
	 * 		.class : Html.BUTTON
	 * 		qtip : First Page
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-first.*)
	 */
	protected GuiTestObject button_firstPage() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_firstPage"));
	}
	/**
	 * firstPage: with specific test context and state.
	 *		type : button
	 * 		.className : RegularExpression(.*x-btn-text x-tbar-page-first.*)
	 * 		.class : Html.BUTTON
	 * 		qtip : First Page
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-first.*)
	 */
	protected GuiTestObject button_firstPage(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_firstPage"), anchor, flags);
	}
	
	/**
	 * lastPage: with default state.
	 *		type : button
	 * 		.className : RegularExpression(.*x-btn-text x-tbar-page-last.*)
	 * 		.class : Html.BUTTON
	 * 		qtip : Last Page
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-last.*)
	 */
	protected GuiTestObject button_lastPage() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_lastPage"));
	}
	/**
	 * lastPage: with specific test context and state.
	 *		type : button
	 * 		.className : RegularExpression(.*x-btn-text x-tbar-page-last.*)
	 * 		.class : Html.BUTTON
	 * 		qtip : Last Page
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-last.*)
	 */
	protected GuiTestObject button_lastPage(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_lastPage"), anchor, flags);
	}
	
	/**
	 * nextPage: with default state.
	 *		type : button
	 * 		.className : RegularExpression(.*x-btn-text x-tbar-page-next.*)
	 * 		.class : Html.BUTTON
	 * 		qtip : Next Page
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-next.*)
	 */
	protected GuiTestObject button_nextPage() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_nextPage"));
	}
	/**
	 * nextPage: with specific test context and state.
	 *		type : button
	 * 		.className : RegularExpression(.*x-btn-text x-tbar-page-next.*)
	 * 		.class : Html.BUTTON
	 * 		qtip : Next Page
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-next.*)
	 */
	protected GuiTestObject button_nextPage(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_nextPage"), anchor, flags);
	}
	
	/**
	 * previousPage: with default state.
	 *		type : button
	 * 		.className : RegularExpression(.*x-btn-text x-tbar-page-prev.*)
	 * 		.class : Html.BUTTON
	 * 		qtip : Previous Page
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-prev.*)
	 */
	protected GuiTestObject button_previousPage() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_previousPage"));
	}
	/**
	 * previousPage: with specific test context and state.
	 *		type : button
	 * 		.className : RegularExpression(.*x-btn-text x-tbar-page-prev.*)
	 * 		.class : Html.BUTTON
	 * 		qtip : Previous Page
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-prev.*)
	 */
	protected GuiTestObject button_previousPage(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_previousPage"), anchor, flags);
	}
	
	

	protected CommonHelper()
	{
		setScriptName("NetmailSearch_General.Common");
	}
	
}

