// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.NetmailSearch_General;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Common</b><br>
 * Generated     : <b>2014/08/07 1:30:01 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  August 07, 2014
 * @author Administrator
 */
public abstract class CommonHelper extends utilities.MySuperHelper
{
	/**
	 * firstPage: with default state.
	 *		type : button
	 * 		.className : RegularExpression(.*x-btn-text x-tbar-page-first.*)
	 * 		.class : Html.BUTTON
	 * 		qtip : First Page
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-first.*)
	 */
	protected GuiTestObject button_firstPage() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_firstPage"));
	}
	/**
	 * firstPage: with specific test context and state.
	 *		type : button
	 * 		.className : RegularExpression(.*x-btn-text x-tbar-page-first.*)
	 * 		.class : Html.BUTTON
	 * 		qtip : First Page
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-first.*)
	 */
	protected GuiTestObject button_firstPage(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_firstPage"), anchor, flags);
	}
	
	/**
	 * lastPage: with default state.
	 *		type : button
	 * 		.className : RegularExpression(.*x-btn-text x-tbar-page-last.*)
	 * 		.class : Html.BUTTON
	 * 		qtip : Last Page
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-last.*)
	 */
	protected GuiTestObject button_lastPage() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_lastPage"));
	}
	/**
	 * lastPage: with specific test context and state.
	 *		type : button
	 * 		.className : RegularExpression(.*x-btn-text x-tbar-page-last.*)
	 * 		.class : Html.BUTTON
	 * 		qtip : Last Page
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-last.*)
	 */
	protected GuiTestObject button_lastPage(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_lastPage"), anchor, flags);
	}
	
	/**
	 * nextPage: with default state.
	 *		type : button
	 * 		.className : RegularExpression(.*x-btn-text x-tbar-page-next.*)
	 * 		.class : Html.BUTTON
	 * 		qtip : Next Page
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-next.*)
	 */
	protected GuiTestObject button_nextPage() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_nextPage"));
	}
	/**
	 * nextPage: with specific test context and state.
	 *		type : button
	 * 		.className : RegularExpression(.*x-btn-text x-tbar-page-next.*)
	 * 		.class : Html.BUTTON
	 * 		qtip : Next Page
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-next.*)
	 */
	protected GuiTestObject button_nextPage(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_nextPage"), anchor, flags);
	}
	
	/**
	 * Preferencesbutton: with default state.
	 *		.text : Preferences
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_preferencesbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_preferencesbutton"));
	}
	/**
	 * Preferencesbutton: with specific test context and state.
	 *		.text : Preferences
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_preferencesbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_preferencesbutton"), anchor, flags);
	}
	
	/**
	 * previousPage: with default state.
	 *		type : button
	 * 		.className : RegularExpression(.*x-btn-text x-tbar-page-prev.*)
	 * 		.class : Html.BUTTON
	 * 		qtip : Previous Page
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-prev.*)
	 */
	protected GuiTestObject button_previousPage() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_previousPage"));
	}
	/**
	 * previousPage: with specific test context and state.
	 *		type : button
	 * 		.className : RegularExpression(.*x-btn-text x-tbar-page-prev.*)
	 * 		.class : Html.BUTTON
	 * 		qtip : Previous Page
	 * 		class : RegularExpression(.*x-btn-text x-tbar-page-prev.*)
	 */
	protected GuiTestObject button_previousPage(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_previousPage"), anchor, flags);
	}
	
	/**
	 * displayingText: with default state.
	 *		.className : xtb-text
	 * 		.class : Html.DIV
	 * 		.contentText : RegularExpression(^Displaying \d+ - \d+ of \d+$)
	 * 		.classIndex : 0
	 * 		class : xtb-text
	 */
	protected GuiTestObject html_displayingText() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_displayingText"));
	}
	/**
	 * displayingText: with specific test context and state.
	 *		.className : xtb-text
	 * 		.class : Html.DIV
	 * 		.contentText : RegularExpression(^Displaying \d+ - \d+ of \d+$)
	 * 		.classIndex : 0
	 * 		class : xtb-text
	 */
	protected GuiTestObject html_displayingText(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_displayingText"), anchor, flags);
	}
	
	/**
	 * pageSize: with default state.
	 *		.text : Page Size
	 * 		.class : Html.A
	 * 		.classIndex : 0
	 * 		class : x-menu-item x-menu-item-arrow
	 */
	protected GuiTestObject link_pageSize() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize"));
	}
	/**
	 * pageSize: with specific test context and state.
	 *		.text : Page Size
	 * 		.class : Html.A
	 * 		.classIndex : 0
	 * 		class : x-menu-item x-menu-item-arrow
	 */
	protected GuiTestObject link_pageSize(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize"), anchor, flags);
	}
	
	/**
	 * pageSize100: with default state.
	 *		.text : 100
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_pageSize100() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize100"));
	}
	/**
	 * pageSize100: with specific test context and state.
	 *		.text : 100
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_pageSize100(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize100"), anchor, flags);
	}
	
	/**
	 * pageSize20: with default state.
	 *		.text : 20
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_pageSize20() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize20"));
	}
	/**
	 * pageSize20: with specific test context and state.
	 *		.text : 20
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_pageSize20(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize20"), anchor, flags);
	}
	
	/**
	 * pageSize200: with default state.
	 *		.text : 200
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_pageSize200() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize200"));
	}
	/**
	 * pageSize200: with specific test context and state.
	 *		.text : 200
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_pageSize200(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize200"), anchor, flags);
	}
	
	/**
	 * pageSize50: with default state.
	 *		.text : 50
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_pageSize50() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize50"));
	}
	/**
	 * pageSize50: with specific test context and state.
	 *		.text : 50
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_pageSize50(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize50"), anchor, flags);
	}
	
	

	protected CommonHelper()
	{
		setScriptName("NetmailSearch_General.Common");
	}
	
}

