// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TC_1333_FilterAndFolderStats;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TS_1454_FilterAndFolder</b><br>
 * Generated     : <b>2014/07/24 11:03:09 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  July 24, 2014
 * @author Administrator
 */
public abstract class TS_1454_FilterAndFolderHelper extends utilities.MySuperHelper
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * Preferencesbutton: with default state.
	 *		.text : Preferences
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_preferencesbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_preferencesbutton"));
	}
	/**
	 * Preferencesbutton: with specific test context and state.
	 *		.text : Preferences
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_preferencesbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_preferencesbutton"), anchor, flags);
	}
	
	/**
	 * expandFilter: with default state.
	 *		.className : x-layout-mini x-layout-mini-south
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_expandFilter() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_expandFilter"));
	}
	/**
	 * expandFilter: with specific test context and state.
	 *		.className : x-layout-mini x-layout-mini-south
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_expandFilter(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_expandFilter"), anchor, flags);
	}
	
	/**
	 * filterTree0Xcollapsed: with default state.
	 *		id : RegularExpression(ext-comp-\d*-xcollapsed)
	 * 		.id : RegularExpression(ext-comp-\d*-xcollapsed)
	 * 		.className : x-layout-collapsed x-layout-collapsed-south x-layout-cmini-south
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_filterTree0Xcollapsed() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_filterTree0Xcollapsed"));
	}
	/**
	 * filterTree0Xcollapsed: with specific test context and state.
	 *		id : RegularExpression(ext-comp-\d*-xcollapsed)
	 * 		.id : RegularExpression(ext-comp-\d*-xcollapsed)
	 * 		.className : x-layout-collapsed x-layout-collapsed-south x-layout-cmini-south
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_filterTree0Xcollapsed(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_filterTree0Xcollapsed"), anchor, flags);
	}
	
	/**
	 * filterTree0Xexpanded: with default state.
	 *		id : RegularExpression(ext-comp-\d*-xsplit)
	 * 		.id : RegularExpression(ext-comp-\d*-xsplit)
	 * 		.className : x-layout-split x-layout-split-south x-splitbar-v
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_filterTree0Xexpanded() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_filterTree0Xexpanded"));
	}
	/**
	 * filterTree0Xexpanded: with specific test context and state.
	 *		id : RegularExpression(ext-comp-\d*-xsplit)
	 * 		.id : RegularExpression(ext-comp-\d*-xsplit)
	 * 		.className : x-layout-split x-layout-split-south x-splitbar-v
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_filterTree0Xexpanded(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_filterTree0Xexpanded"), anchor, flags);
	}
	
	/**
	 * filterUL: with default state.
	 *		.class : Html.UL
	 * 		class : x-tree-root-ct x-tree-arrows
	 */
	protected GuiTestObject html_filterUL() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_filterUL"));
	}
	/**
	 * filterUL: with specific test context and state.
	 *		.class : Html.UL
	 * 		class : x-tree-root-ct x-tree-arrows
	 */
	protected GuiTestObject html_filterUL(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_filterUL"), anchor, flags);
	}
	
	/**
	 * folderUL: with default state.
	 *		.class : Html.UL
	 * 		class : x-tree-root-ct x-tree-arrows
	 */
	protected GuiTestObject html_folderUL() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_folderUL"));
	}
	/**
	 * folderUL: with specific test context and state.
	 *		.class : Html.UL
	 * 		class : x-tree-root-ct x-tree-arrows
	 */
	protected GuiTestObject html_folderUL(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_folderUL"), anchor, flags);
	}
	
	/**
	 * msgCloseButton: with default state.
	 *		.className : x-tool x-tool-close
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_msgCloseButton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_msgCloseButton"));
	}
	/**
	 * msgCloseButton: with specific test context and state.
	 *		.className : x-tool x-tool-close
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_msgCloseButton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_msgCloseButton"), anchor, flags);
	}
	
	/**
	 * msgPropertyOpened: with default state.
	 *		.text : Opened
	 * 		.class : Html.A
	 * 		class : x-tree-node-anchor
	 */
	protected GuiTestObject link_msgPropertyOpened() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_msgPropertyOpened"));
	}
	/**
	 * msgPropertyOpened: with specific test context and state.
	 *		.text : Opened
	 * 		.class : Html.A
	 * 		class : x-tree-node-anchor
	 */
	protected GuiTestObject link_msgPropertyOpened(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_msgPropertyOpened"), anchor, flags);
	}
	
	/**
	 * msgPropertyRead: with default state.
	 *		.text : Read
	 * 		.class : Html.A
	 * 		class : x-tree-node-anchor
	 */
	protected GuiTestObject link_msgPropertyRead() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_msgPropertyRead"));
	}
	/**
	 * msgPropertyRead: with specific test context and state.
	 *		.text : Read
	 * 		.class : Html.A
	 * 		class : x-tree-node-anchor
	 */
	protected GuiTestObject link_msgPropertyRead(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_msgPropertyRead"), anchor, flags);
	}
	
	/**
	 * msgPropertyTab: with default state.
	 *		.text : Properties
	 * 		.class : Html.A
	 * 		class : x-tab-right
	 */
	protected GuiTestObject link_msgPropertyTab() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_msgPropertyTab"));
	}
	/**
	 * msgPropertyTab: with specific test context and state.
	 *		.text : Properties
	 * 		.class : Html.A
	 * 		class : x-tab-right
	 */
	protected GuiTestObject link_msgPropertyTab(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_msgPropertyTab"), anchor, flags);
	}
	
	/**
	 * pageSize: with default state.
	 *		.text : Page Size
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-item-arrow
	 */
	protected GuiTestObject link_pageSize() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize"));
	}
	/**
	 * pageSize: with specific test context and state.
	 *		.text : Page Size
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-item-arrow
	 */
	protected GuiTestObject link_pageSize(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize"), anchor, flags);
	}
	
	/**
	 * pageSize_200: with default state.
	 *		.text : 200
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_pageSize_200() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize_200"));
	}
	/**
	 * pageSize_200: with specific test context and state.
	 *		.text : 200
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item x-menu-group-item
	 */
	protected GuiTestObject link_pageSize_200(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_pageSize_200"), anchor, flags);
	}
	
	/**
	 * quickSearchField0: with default state.
	 *		type : text
	 * 		.id : quickSearchField0
	 * 		.class : Html.INPUT.text
	 * 		name : quickSearchField0
	 * 		class : x-form-text x-form-field search_field_effect x-form-empty-field
	 */
	protected TextGuiTestObject text_quickSearchField0() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_quickSearchField0"));
	}
	/**
	 * quickSearchField0: with specific test context and state.
	 *		type : text
	 * 		.id : quickSearchField0
	 * 		.class : Html.INPUT.text
	 * 		name : quickSearchField0
	 * 		class : x-form-text x-form-field search_field_effect x-form-empty-field
	 */
	protected TextGuiTestObject text_quickSearchField0(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_quickSearchField0"), anchor, flags);
	}
	
	

	protected TS_1454_FilterAndFolderHelper()
	{
		setScriptName("TC_1333_FilterAndFolderStats.TS_1454_FilterAndFolder");
	}
	
}

