// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TC_978_ExportPortableNetmailSearch;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TS_992_AddTagsAndComments_NetmailLite</b><br>
 * Generated     : <b>2014/04/15 4:44:20 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  April 15, 2014
 * @author Administrator
 */
public abstract class TS_992_AddTagsAndComments_NetmailLiteHelper extends utilities.MySuperHelper
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * addComment: with default state.
	 *		.text : 
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text comment-tb-icon
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_addComment() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_addComment"));
	}
	/**
	 * addComment: with specific test context and state.
	 *		.text : 
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text comment-tb-icon
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_addComment(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_addComment"), anchor, flags);
	}
	
	/**
	 * Flaggedbutton: with default state.
	 *		.text : Flagged
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_flaggedbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_flaggedbutton"));
	}
	/**
	 * Flaggedbutton: with specific test context and state.
	 *		.text : Flagged
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_flaggedbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_flaggedbutton"), anchor, flags);
	}
	
	/**
	 * Privilegebutton: with default state.
	 *		.text : Privileged
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_privilegebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_privilegebutton"));
	}
	/**
	 * Privilegebutton: with specific test context and state.
	 *		.text : Privileged
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_privilegebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_privilegebutton"), anchor, flags);
	}
	
	/**
	 * Relevantbutton: with default state.
	 *		.text : Relevant
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_relevantbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_relevantbutton"));
	}
	/**
	 * Relevantbutton: with specific test context and state.
	 *		.text : Relevant
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		class :  x-btn-text
	 */
	protected GuiTestObject button_relevantbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_relevantbutton"), anchor, flags);
	}
	
	/**
	 * RemoveTagbutton: with default state.
	 *		.text : Remove tag
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_removeTagbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_removeTagbutton"));
	}
	/**
	 * RemoveTagbutton: with specific test context and state.
	 *		.text : Remove tag
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_removeTagbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_removeTagbutton"), anchor, flags);
	}
	
	/**
	 * taggOK: with default state.
	 *		.text : OK
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_taggOK() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_taggOK"));
	}
	/**
	 * taggOK: with specific test context and state.
	 *		.text : OK
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_taggOK(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_taggOK"), anchor, flags);
	}
	
	/**
	 * WorkProductbutton: with default state.
	 *		.text : Work Product
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_workProductbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_workProductbutton"));
	}
	/**
	 * WorkProductbutton: with specific test context and state.
	 *		.text : Work Product
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_workProductbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_workProductbutton"), anchor, flags);
	}
	
	/**
	 * extGen3: with default state.
	 *		.class : Html.BODY
	 */
	protected GuiTestObject html_extGen3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen3"));
	}
	/**
	 * extGen3: with specific test context and state.
	 *		.class : Html.BODY
	 */
	protected GuiTestObject html_extGen3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_extGen3"), anchor, flags);
	}
	
	/**
	 * removeTagEM: with default state.
	 *		.text : Remove tag
	 * 		.title : 
	 * 		.class : Html.EM
	 * 		class : x-btn-split
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_removeTagEM() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_removeTagEM"));
	}
	/**
	 * removeTagEM: with specific test context and state.
	 *		.text : Remove tag
	 * 		.title : 
	 * 		.class : Html.EM
	 * 		class : x-btn-split
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_removeTagEM(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_removeTagEM"), anchor, flags);
	}
	
	/**
	 * tagAppliedMSG: with default state.
	 *		.text : Tag applied successfully.
	 * 		.className : ext-mb-text
	 * 		.title : 
	 * 		.class : Html.SPAN
	 */
	protected GuiTestObject html_tagAppliedMSG() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_tagAppliedMSG"));
	}
	/**
	 * tagAppliedMSG: with specific test context and state.
	 *		.text : Tag applied successfully.
	 * 		.className : ext-mb-text
	 * 		.title : 
	 * 		.class : Html.SPAN
	 */
	protected GuiTestObject html_tagAppliedMSG(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_tagAppliedMSG"), anchor, flags);
	}
	
	/**
	 * columns: with default state.
	 *		.text : Columns
	 * 		.href : http://localhost:50878/index.html?dp-mode=lite#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item x-menu-item-arrow
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_columns() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_columns"));
	}
	/**
	 * columns: with specific test context and state.
	 *		.text : Columns
	 * 		.href : http://localhost:50878/index.html?dp-mode=lite#
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		class : x-menu-item x-menu-item-arrow
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_columns(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_columns"), anchor, flags);
	}
	
	/**
	 * comment: with default state.
	 *		.text : Comment
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item
	 */
	protected GuiTestObject link_comment() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_comment"));
	}
	/**
	 * comment: with specific test context and state.
	 *		.text : Comment
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item
	 */
	protected GuiTestObject link_comment(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_comment"), anchor, flags);
	}
	
	/**
	 * Date: with default state.
	 *		.text : Date
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item
	 */
	protected GuiTestObject link_date() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_date"));
	}
	/**
	 * Date: with specific test context and state.
	 *		.text : Date
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item
	 */
	protected GuiTestObject link_date(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_date"), anchor, flags);
	}
	
	/**
	 * expander: with default state.
	 *		.text : Expander
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item
	 */
	protected GuiTestObject link_expander() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_expander"));
	}
	/**
	 * expander: with specific test context and state.
	 *		.text : Expander
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item
	 */
	protected GuiTestObject link_expander(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_expander"), anchor, flags);
	}
	
	/**
	 * from: with default state.
	 *		.text : From
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item
	 */
	protected GuiTestObject link_from() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_from"));
	}
	/**
	 * from: with specific test context and state.
	 *		.text : From
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item
	 */
	protected GuiTestObject link_from(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_from"), anchor, flags);
	}
	
	/**
	 * rmvFlagged: with default state.
	 *		.text : Flagged
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_rmvFlagged() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_rmvFlagged"));
	}
	/**
	 * rmvFlagged: with specific test context and state.
	 *		.text : Flagged
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_rmvFlagged(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_rmvFlagged"), anchor, flags);
	}
	
	/**
	 * rmvPrivilege: with default state.
	 *		.text : Privileged
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 */
	protected GuiTestObject link_rmvPrivilege() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_rmvPrivilege"));
	}
	/**
	 * rmvPrivilege: with specific test context and state.
	 *		.text : Privileged
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 */
	protected GuiTestObject link_rmvPrivilege(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_rmvPrivilege"), anchor, flags);
	}
	
	/**
	 * rmvRelevant: with default state.
	 *		.text : Relevant
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_rmvRelevant() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_rmvRelevant"));
	}
	/**
	 * rmvRelevant: with specific test context and state.
	 *		.text : Relevant
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_rmvRelevant(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_rmvRelevant"), anchor, flags);
	}
	
	/**
	 * rmvWorkProduct: with default state.
	 *		.text : Work Product
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_rmvWorkProduct() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_rmvWorkProduct"));
	}
	/**
	 * rmvWorkProduct: with specific test context and state.
	 *		.text : Work Product
	 * 		.class : Html.A
	 * 		class : x-menu-item
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_rmvWorkProduct(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_rmvWorkProduct"), anchor, flags);
	}
	
	/**
	 * tags: with default state.
	 *		.text : Tags
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item
	 */
	protected GuiTestObject link_tags() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_tags"));
	}
	/**
	 * tags: with specific test context and state.
	 *		.text : Tags
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item
	 */
	protected GuiTestObject link_tags(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_tags"), anchor, flags);
	}
	
	/**
	 * tampered: with default state.
	 *		.text : Tampered
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item
	 */
	protected GuiTestObject link_tampered() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_tampered"));
	}
	/**
	 * tampered: with specific test context and state.
	 *		.text : Tampered
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item
	 */
	protected GuiTestObject link_tampered(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_tampered"), anchor, flags);
	}
	
	/**
	 * to: with default state.
	 *		.text : To
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item
	 */
	protected GuiTestObject link_to() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_to"));
	}
	/**
	 * to: with specific test context and state.
	 *		.text : To
	 * 		.class : Html.A
	 * 		class : x-menu-item x-menu-check-item
	 */
	protected GuiTestObject link_to(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_to"), anchor, flags);
	}
	
	/**
	 * comment: with default state.
	 *		type : text
	 * 		.class : Html.INPUT.text
	 * 		class : x-form-text x-form-field
	 */
	protected TextGuiTestObject text_comment() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_comment"));
	}
	/**
	 * comment: with specific test context and state.
	 *		type : text
	 * 		.class : Html.INPUT.text
	 * 		class : x-form-text x-form-field
	 */
	protected TextGuiTestObject text_comment(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_comment"), anchor, flags);
	}
	
	/**
	 * quickSearchField0: with default state.
	 *		type : text
	 * 		.id : quickSearchField0
	 * 		.class : Html.INPUT.text
	 * 		name : quickSearchField0
	 * 		.classIndex : 0
	 * 		class : x-form-text x-form-field search_field_effect x-form-empty-field
	 */
	protected TextGuiTestObject text_quickSearchField0() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_quickSearchField0"));
	}
	/**
	 * quickSearchField0: with specific test context and state.
	 *		type : text
	 * 		.id : quickSearchField0
	 * 		.class : Html.INPUT.text
	 * 		name : quickSearchField0
	 * 		.classIndex : 0
	 * 		class : x-form-text x-form-field search_field_effect x-form-empty-field
	 */
	protected TextGuiTestObject text_quickSearchField0(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_quickSearchField0"), anchor, flags);
	}
	
	

	protected TS_992_AddTagsAndComments_NetmailLiteHelper()
	{
		setScriptName("TC_978_ExportPortableNetmailSearch.TS_992_AddTagsAndComments_NetmailLite");
	}
	
}

