// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TC_978_ExportPortableNetmailSearch;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TS_PortableAuditOption</b><br>
 * Generated     : <b>2014/08/05 2:16:16 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  August 05, 2014
 * @author Administrator
 */
public abstract class TS_PortableAuditOptionHelper extends utilities.MySuperHelper
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * messageClose: with default state.
	 *		.className : x-tool x-tool-close
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_messageClose() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_messageClose"));
	}
	/**
	 * messageClose: with specific test context and state.
	 *		.className : x-tool x-tool-close
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_messageClose(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_messageClose"), anchor, flags);
	}
	
	/**
	 * messageWindow0: with default state.
	 *		id : messageWindow0
	 * 		.id : messageWindow0
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_messageWindow0() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_messageWindow0"));
	}
	/**
	 * messageWindow0: with specific test context and state.
	 *		id : messageWindow0
	 * 		.id : messageWindow0
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_messageWindow0(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_messageWindow0"), anchor, flags);
	}
	
	/**
	 * auditTab: with default state.
	 *		.text : Audit
	 * 		.class : Html.A
	 * 		.contentText : Audit
	 * 		class : x-tab-right
	 */
	protected GuiTestObject link_auditTab() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_auditTab"));
	}
	/**
	 * auditTab: with specific test context and state.
	 *		.text : Audit
	 * 		.class : Html.A
	 * 		.contentText : Audit
	 * 		class : x-tab-right
	 */
	protected GuiTestObject link_auditTab(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_auditTab"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.class : Html.TABLE
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.class : Html.TABLE
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.class : Html.TABLE
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_2"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.class : Html.TABLE
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_2"), anchor, flags);
	}
	
	

	protected TS_PortableAuditOptionHelper()
	{
		setScriptName("TC_978_ExportPortableNetmailSearch.TS_PortableAuditOption");
	}
	
}

