// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TEST</b><br>
 * Generated     : <b>2014/07/30 3:00:52 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  July 30, 2014
 * @author Administrator
 */
public abstract class TESTHelper extends utilities.MySuperHelper
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * RFTOutlookWebApp: with default state.
	 *		.title : RFT - Outlook Web App
	 * 		.class : Html.HtmlDocument
	 */
	protected DocumentTestObject document_rftOutlookWebApp() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_rftOutlookWebApp"));
	}
	/**
	 * RFTOutlookWebApp: with specific test context and state.
	 *		.title : RFT - Outlook Web App
	 * 		.class : Html.HtmlDocument
	 */
	protected DocumentTestObject document_rftOutlookWebApp(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_rftOutlookWebApp"), anchor, flags);
	}
	
	/**
	 * _ariaId_143: with default state.
	 *		.className : contextMenuDropShadow contextMenuPopup removeFocusOutline
	 * 		.class : Html.DIV
	 * 		.classIndex : 17
	 */
	protected GuiTestObject html__ariaId_143() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html__ariaId_143"));
	}
	/**
	 * _ariaId_143: with specific test context and state.
	 *		.className : contextMenuDropShadow contextMenuPopup removeFocusOutline
	 * 		.class : Html.DIV
	 * 		.classIndex : 17
	 */
	protected GuiTestObject html__ariaId_143(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html__ariaId_143"), anchor, flags);
	}
	
	/**
	 * _ariaId_40: with default state.
	 *		.id : _ariaId_40
	 * 		.class : Html.DIV
	 * 		.contentText : RegularExpression(.*Inbox.*)
	 */
	protected GuiTestObject html__ariaId_40_2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html__ariaId_40_2"));
	}
	/**
	 * _ariaId_40: with specific test context and state.
	 *		.id : _ariaId_40
	 * 		.class : Html.DIV
	 * 		.contentText : RegularExpression(.*Inbox.*)
	 */
	protected GuiTestObject html__ariaId_40_2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html__ariaId_40_2"), anchor, flags);
	}
	
	/**
	 * JTable: with default state.
	 *		.class : javax.swing.JTable
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject jTable() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("jTable"));
	}
	/**
	 * JTable: with specific test context and state.
	 *		.class : javax.swing.JTable
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject jTable(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("jTable"), anchor, flags);
	}
	
	/**
	 * JTree: with default state.
	 *		.class : javax.swing.JTree
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject jTree() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("jTree"));
	}
	/**
	 * JTree: with specific test context and state.
	 *		.class : javax.swing.JTree
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject jTree(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("jTree"), anchor, flags);
	}
	
	/**
	 * MigrationCompletedReport: with default state.
	 *		.text : Migration Completed Report
	 * 		.class : TForm10
	 * 		.processName : tm11.exe
	 * 		.name : Migration Completed Report
	 */
	protected TopLevelSubitemTestObject migrationCompletedReportwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("migrationCompletedReportwindow"));
	}
	/**
	 * MigrationCompletedReport: with specific test context and state.
	 *		.text : Migration Completed Report
	 * 		.class : TForm10
	 * 		.processName : tm11.exe
	 * 		.name : Migration Completed Report
	 */
	protected TopLevelSubitemTestObject migrationCompletedReportwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("migrationCompletedReportwindow"), anchor, flags);
	}
	
	

	protected TESTHelper()
	{
		setScriptName("TEST");
	}
	
}

