// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TEST</b><br>
 * Generated     : <b>2014/08/13 3:18:05 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  August 13, 2014
 * @author Administrator
 */
public abstract class TESTHelper extends utilities.MySuperHelper
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * RFTOutlookWebApp: with default state.
	 *		.class : Html.HtmlDocument
	 */
	protected DocumentTestObject document_rftOutlookWebApp() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_rftOutlookWebApp"));
	}
	/**
	 * RFTOutlookWebApp: with specific test context and state.
	 *		.class : Html.HtmlDocument
	 */
	protected DocumentTestObject document_rftOutlookWebApp(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_rftOutlookWebApp"), anchor, flags);
	}
	
	/**
	 * Details: with default state.
	 *		.text : Address Book Cache Cached Address Book Update Settings Run cache update process  ...
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : Details
	 * 		class : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_details() 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_details"));
	}
	/**
	 * Details: with specific test context and state.
	 *		.text : Address Book Cache Cached Address Book Update Settings Run cache update process  ...
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : Details
	 * 		class : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_details(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_details"), anchor, flags);
	}
	
	/**
	 * Details: with default state.
	 *		.text : Address Book Cache Cached Address Book Update Settings Run cache update process  ...
	 * 		.class : Html.FORM
	 * 		.title : 
	 * 		.name : Details
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_details2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_details2"));
	}
	/**
	 * Details: with specific test context and state.
	 *		.text : Address Book Cache Cached Address Book Update Settings Run cache update process  ...
	 * 		.class : Html.FORM
	 * 		.title : 
	 * 		.name : Details
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_details2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_details2"), anchor, flags);
	}
	
	/**
	 * _ariaId_143: with default state.
	 *		.text : create new folder rename delete empty remove from Favorites move... mark all as  ...
	 * 		.className : contextMenuDropShadow contextMenuPopup removeFocusOutline
	 * 		.class : Html.DIV
	 * 		.classIndex : 17
	 */
	protected GuiTestObject html__ariaId_143() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html__ariaId_143"));
	}
	/**
	 * _ariaId_143: with specific test context and state.
	 *		.text : create new folder rename delete empty remove from Favorites move... mark all as  ...
	 * 		.className : contextMenuDropShadow contextMenuPopup removeFocusOutline
	 * 		.class : Html.DIV
	 * 		.classIndex : 17
	 */
	protected GuiTestObject html__ariaId_143(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html__ariaId_143"), anchor, flags);
	}
	
	/**
	 * _ariaId_40: with default state.
	 *		.id : _ariaId_40
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html__ariaId_40_2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html__ariaId_40_2"));
	}
	/**
	 * _ariaId_40: with specific test context and state.
	 *		.id : _ariaId_40
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html__ariaId_40_2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html__ariaId_40_2"), anchor, flags);
	}
	
	/**
	 * admin: with default state.
	 *		.className : widget_admin hasResizeHandler
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_admin() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_admin"));
	}
	/**
	 * admin: with specific test context and state.
	 *		.className : widget_admin hasResizeHandler
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_admin(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_admin"), anchor, flags);
	}
	
	/**
	 * asdhiasdo: with default state.
	 *		.className : x-panel-body x-panel-body-noheader x-panel-body-noborder
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_asdhiasdo() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_asdhiasdo"));
	}
	/**
	 * asdhiasdo: with specific test context and state.
	 *		.className : x-panel-body x-panel-body-noheader x-panel-body-noborder
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_asdhiasdo(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_asdhiasdo"), anchor, flags);
	}
	
	/**
	 * editConf: with default state.
	 *		.id : editConf
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_editConf() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_editConf"));
	}
	/**
	 * editConf: with specific test context and state.
	 *		.id : editConf
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_editConf(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_editConf"), anchor, flags);
	}
	
	/**
	 * framework: with default state.
	 *		.className : widget_mplusFramework hasResizeHandler
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_framework() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_framework"));
	}
	/**
	 * framework: with specific test context and state.
	 *		.className : widget_mplusFramework hasResizeHandler
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_framework(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_framework"), anchor, flags);
	}
	
	/**
	 * UL: with default state.
	 *		.text : netmail Plattform Secure Archive Cluster (10.1.30.64) Agenten Knoten Richtlinien ...
	 * 		.title : 
	 * 		.class : Html.UL
	 * 		.classIndex : 0
	 * 		class : x-tree-root-ct x-tree-arrows
	 */
	protected GuiTestObject html_ul() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_ul"));
	}
	/**
	 * UL: with specific test context and state.
	 *		.text : netmail Plattform Secure Archive Cluster (10.1.30.64) Agenten Knoten Richtlinien ...
	 * 		.title : 
	 * 		.class : Html.UL
	 * 		.classIndex : 0
	 * 		class : x-tree-root-ct x-tree-arrows
	 */
	protected GuiTestObject html_ul(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_ul"), anchor, flags);
	}
	
	/**
	 * JTable: with default state.
	 *		.class : javax.swing.JTable
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject jTable() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("jTable"));
	}
	/**
	 * JTable: with specific test context and state.
	 *		.class : javax.swing.JTable
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject jTable(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("jTable"), anchor, flags);
	}
	
	/**
	 * JTree: with default state.
	 *		.class : javax.swing.JTree
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject jTree() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("jTree"));
	}
	/**
	 * JTree: with specific test context and state.
	 *		.class : javax.swing.JTree
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject jTree(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("jTree"), anchor, flags);
	}
	
	/**
	 * MigrationCompletedReport: with default state.
	 *		.text : Migration Completed Report
	 * 		.class : TForm10
	 * 		.processName : tm11.exe
	 * 		.name : Migration Completed Report
	 */
	protected TopLevelSubitemTestObject migrationCompletedReportwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("migrationCompletedReportwindow"));
	}
	/**
	 * MigrationCompletedReport: with specific test context and state.
	 *		.text : Migration Completed Report
	 * 		.class : TForm10
	 * 		.processName : tm11.exe
	 * 		.name : Migration Completed Report
	 */
	protected TopLevelSubitemTestObject migrationCompletedReportwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("migrationCompletedReportwindow"), anchor, flags);
	}
	
	

	protected TESTHelper()
	{
		setScriptName("TEST");
	}
	
}

