// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TEST2</b><br>
 * Generated     : <b>2014/07/30 3:22:57 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  July 30, 2014
 * @author Administrator
 */
public abstract class TEST2Helper extends utilities.MySuperHelper
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * okbutton: with default state.
	 *		.text : ok
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 28
	 * 		class : _b_s o365button o365buttonOutlined o365buttonOutlinedHovered
	 */
	protected GuiTestObject button_okbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_okbutton"));
	}
	/**
	 * okbutton: with specific test context and state.
	 *		.text : ok
	 * 		type : button
	 * 		.class : Html.BUTTON
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 28
	 * 		class : _b_s o365button o365buttonOutlined o365buttonOutlinedHovered
	 */
	protected GuiTestObject button_okbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_okbutton"), anchor, flags);
	}
	
	/**
	 * RFTOutlookWebApp: with default state.
	 *		.class : Html.HtmlDocument
	 * 		.title : RFT - Outlook Web App
	 */
	protected DocumentTestObject document_rftOutlookWebApp() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_rftOutlookWebApp"));
	}
	/**
	 * RFTOutlookWebApp: with specific test context and state.
	 *		.class : Html.HtmlDocument
	 * 		.title : RFT - Outlook Web App
	 */
	protected DocumentTestObject document_rftOutlookWebApp(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_rftOutlookWebApp"), anchor, flags);
	}
	
	/**
	 * _ariaId_146: with default state.
	 *		.className : contextMenuDropShadow contextMenuPopup removeFocusOutline
	 * 		.class : Html.DIV
	 * 		.classIndex : 17
	 */
	protected GuiTestObject html__ariaId_146() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html__ariaId_146"));
	}
	/**
	 * _ariaId_146: with specific test context and state.
	 *		.className : contextMenuDropShadow contextMenuPopup removeFocusOutline
	 * 		.class : Html.DIV
	 * 		.classIndex : 17
	 */
	protected GuiTestObject html__ariaId_146(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html__ariaId_146"), anchor, flags);
	}
	
	/**
	 * Inbox: with default state.
	 *		.text : Inbox
	 * 		.className : _n_X7 _n_Y7
	 * 		.class : Html.SPAN
	 * 		.title : Inbox
	 */
	protected GuiTestObject html_inbox() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_inbox"));
	}
	/**
	 * Inbox: with specific test context and state.
	 *		.text : Inbox
	 * 		.className : _n_X7 _n_Y7
	 * 		.class : Html.SPAN
	 * 		.title : Inbox
	 */
	protected GuiTestObject html_inbox(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_inbox"), anchor, flags);
	}
	
	

	protected TEST2Helper()
	{
		setScriptName("TEST2");
	}
	
}

