// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TC_827_NetmailSearch_Search;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TS_988_CaseManagement</b><br>
 * Generated     : <b>2013/08/02 11:45:14 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  August 02, 2013
 * @author Administrator
 */
public abstract class TS_988_CaseManagementHelper extends RationalTestScript
{
	/**
	 * Cancelbutton: with default state.
	 *		.text : Cancel
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text cancel-tb-icon
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_cancelbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_cancelbutton"));
	}
	/**
	 * Cancelbutton: with specific test context and state.
	 *		.text : Cancel
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text cancel-tb-icon
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_cancelbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_cancelbutton"), anchor, flags);
	}
	
	/**
	 * deleteCase_Nobutton: with default state.
	 *		.text : No
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_deleteCase_Nobutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_deleteCase_Nobutton"));
	}
	/**
	 * deleteCase_Nobutton: with specific test context and state.
	 *		.text : No
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_deleteCase_Nobutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_deleteCase_Nobutton"), anchor, flags);
	}
	
	/**
	 * deleteCase_Yesbutton: with default state.
	 *		.text : Yes
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_deleteCase_Yesbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_deleteCase_Yesbutton"));
	}
	/**
	 * deleteCase_Yesbutton: with specific test context and state.
	 *		.text : Yes
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_deleteCase_Yesbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_deleteCase_Yesbutton"), anchor, flags);
	}
	
	/**
	 * DeleteCasebutton: with default state.
	 *		.text : Delete Case
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text delete-tb-icon
	 */
	protected GuiTestObject button_deleteCasebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_deleteCasebutton"));
	}
	/**
	 * DeleteCasebutton: with specific test context and state.
	 *		.text : Delete Case
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text delete-tb-icon
	 */
	protected GuiTestObject button_deleteCasebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_deleteCasebutton"), anchor, flags);
	}
	
	/**
	 * EditCasebutton: with default state.
	 *		.text : Edit Case
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text edit-tb-icon
	 */
	protected GuiTestObject button_editCasebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_editCasebutton"));
	}
	/**
	 * EditCasebutton: with specific test context and state.
	 *		.text : Edit Case
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text edit-tb-icon
	 */
	protected GuiTestObject button_editCasebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_editCasebutton"), anchor, flags);
	}
	
	/**
	 * NewCasebutton: with default state.
	 *		.text : New Case
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text new-tb-icon
	 */
	protected GuiTestObject button_newCasebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_newCasebutton"));
	}
	/**
	 * NewCasebutton: with specific test context and state.
	 *		.text : New Case
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 * 		class :  x-btn-text new-tb-icon
	 */
	protected GuiTestObject button_newCasebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_newCasebutton"), anchor, flags);
	}
	
	/**
	 * OpenCasebutton: with default state.
	 *		.text : Open Case
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text load-tb-icon
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_openCasebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_openCasebutton"));
	}
	/**
	 * OpenCasebutton: with specific test context and state.
	 *		.text : Open Case
	 * 		type : button
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		class :  x-btn-text load-tb-icon
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_openCasebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_openCasebutton"), anchor, flags);
	}
	
	/**
	 * caseListWindow: with default state.
	 *		.id : caseListWindow
	 * 		.className : x-window x-window-noborder x-window-plain x-resizable-pinned
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_caseListWindow() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_caseListWindow"));
	}
	/**
	 * caseListWindow: with specific test context and state.
	 *		.id : caseListWindow
	 * 		.className : x-window x-window-noborder x-window-plain x-resizable-pinned
	 * 		.class : Html.DIV
	 */
	protected GuiTestObject html_caseListWindow(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_caseListWindow"), anchor, flags);
	}
	
	

	protected TS_988_CaseManagementHelper()
	{
		setScriptName("TC_827_NetmailSearch_Search.TS_988_CaseManagement");
	}
	
}

