// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.TC_827_NetmailSearch_Search;
import utilities.MySuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TS_987_Search_AdvanceSearch_Messages_NetmailSearch</b><br>
 * Generated     : <b>2013/07/15 9:51:21 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows Server 2008 R2 x86 6.1 <br>
 * 
 * @since  July 15, 2013
 * @author Administrator
 */
public abstract class TS_987_Search_AdvanceSearch_Messages_NetmailSearchHelper extends utilities.MySuperHelper
{
	

	protected TS_987_Search_AdvanceSearch_Messages_NetmailSearchHelper()
	{
		setScriptName("TC_827_NetmailSearch_Search.TS_987_Search_AdvanceSearch_Messages_NetmailSearch");
	}
	
}

